/**
 * CLASS 9: ELECTRONICS & BATTERIES (15 SKUs)
 * E-waste components, batteries (Li-ion, lead-acid, NiMH), solar panels
 * Focus on recoverable materials and hazardous streams
 */

import { MaterialSKU, MaterialClass } from './types';

export const ELECTRONICS_BATTERIES: MaterialSKU[] = [
  // 9.1 BATTERIES - 6 SKUs
  {
    id: '9.1.1-lithium-ion-battery',
    class: 9,
    subclass: '9.1',
    sku: 'BATT-LIION',
    tradeName: 'Lithium-Ion Batteries',
    alternativeNames: ['Li-ion batteries', 'EV batteries', 'Laptop batteries'],
    ewcCode: '16 06 01*',
    ewcDescription: 'lead batteries',
    wasteTier: 'T4',
    wasteTierDescription: 'Hazardous waste - fire/explosion risk',
    hazard: {
      unNumber: 'UN 3480',
      adrClass: '9',
      packingGroup: 'II',
      hProperties: ['H3', 'H5', 'H14'],
      transportRestrictions: 'Class 9 dangerous goods. Must be <30% SoC. Fire precautions. Special packaging.',
    },
    specifications: {
      composition: [
        { element: 'Lithium', range: { min: 1, max: 3 }, unit: '%' },
        { element: 'Cobalt', range: { min: 5, max: 20 }, unit: '%' },
        { element: 'Nickel', range: { min: 10, max: 35 }, unit: '%' },
        { element: 'Copper', range: { min: 10, max: 20 }, unit: '%' },
        { element: 'Aluminum', range: { min: 5, max: 15 }, unit: '%' },
        { element: 'Graphite', range: { min: 10, max: 20 }, unit: '%' },
      ],
      physicalForm: 'Battery packs, cells',
      bulkDensity: { min: 400, max: 700, unit: 'kg/mÂ³' },
    },
    pricing: {
      basePrice: 1850,
      unit: 't',
      range: { min: 800, max: 3500 },
      marketIndex: 'LME',
      updateFrequency: 'daily',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'EV battery packs, >80% capacity, reuse-grade', priceMultiplier: 2.20, contaminationMax: 5.0, certificationRequired: true },
      { tier: 'Q2', requirements: 'Recyclable packs, discharged, known chemistry', priceMultiplier: 1.0, contaminationMax: 10.0, certificationRequired: true },
      { tier: 'Q3', requirements: 'Mixed battery types, lower cobalt content', priceMultiplier: 0.65, contaminationMax: 20.0, certificationRequired: true },
    ],
    processing: {
      recyclingRoutes: ['Pyrometallurgical recovery', 'Hydrometallurgical recovery', 'Direct recycling', 'Second-life energy storage'],
      specialRequirements: 'MUST discharge to <30% SoC. Fire suppression required. Hazmat license. Test for capacity (reuse).',
      difficulty: 'very-hard',
      energyRequired: 3.5,
      equipmentNeeded: ['Discharge station', 'Shredder', 'Black mass recovery', 'Fire suppression', 'Hydromet/pyromet plant'],
    },
    marketData: {
      demand: 'very-high',
      supply: 'medium',
      volatility: 'high',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 850,
      carbonAvoided: 8150,
      recyclabilityScore: 70,
      maxRecycleLoops: 2,
    },
    typicalSources: ['Electric vehicle dismantlers', 'Electronics recyclers', 'Battery swapping stations'],
    endMarkets: ['Battery material refining', 'Second-life storage', 'Black mass smelters'],
    notes: 'Extreme high value. Cobalt/Nickel recovery. Fire risk major concern. Second-life growing. Price volatile (cobalt swings).',
  },

  {
    id: '9.1.2-lead-acid-battery',
    class: 9,
    subclass: '9.1',
    sku: 'BATT-LEAD',
    tradeName: 'Lead-Acid Batteries',
    alternativeNames: ['Car batteries', 'SLI batteries', 'Forklift batteries'],
    ewcCode: '16 06 01*',
    ewcDescription: 'lead batteries',
    wasteTier: 'T4',
    wasteTierDescription: 'Hazardous waste - toxic lead',
    hazard: {
      unNumber: 'UN 2794',
      adrClass: '8',
      packingGroup: 'II',
      hProperties: ['H5', 'H6', 'H8', 'H14'],
      transportRestrictions: 'Corrosive + toxic. ADR Class 8. Leak-proof packaging. No tipping.',
    },
    specifications: {
      composition: [
        { element: 'Lead', range: { min: 60, max: 70 }, unit: '%' },
        { element: 'Sulfuric acid', range: { min: 15, max: 25 }, unit: '%' },
        { element: 'Polypropylene (case)', range: { min: 5, max: 10 }, unit: '%' },
      ],
      physicalForm: 'Battery units',
      bulkDensity: { min: 1100, max: 1300, unit: 'kg/mÂ³' },
    },
    pricing: {
      basePrice: 420,
      unit: 't',
      range: { min: 320, max: 580 },
      marketIndex: 'LME',
      updateFrequency: 'daily',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Intact batteries, acid contained, no leaks', priceMultiplier: 1.15, contaminationMax: 5.0, certificationRequired: true },
      { tier: 'Q2', requirements: 'Standard used batteries', priceMultiplier: 1.0, contaminationMax: 10.0, certificationRequired: true },
      { tier: 'Q3', requirements: 'Damaged, leaking, mixed types', priceMultiplier: 0.75, contaminationMax: 20.0, certificationRequired: true },],
      processing: {
        recyclingRoutes: ['Lead smelting', 'Acid recovery', 'Plastic recycling'],
      specialRequirements: 'Hazmat license required. Acid neutralization. Lead exposure controls.',
      difficulty: 'medium',
      energyRequired: 1.8,
      equipmentNeeded: ['Crusher/breaker', 'Acid drain', 'Lead furnace', 'PP separator'],
    },
    marketData: {
      demand: 'very-high',
      supply: 'very-high',
      volatility: 'medium',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 380,
      carbonAvoided: 1520,
      recyclabilityScore: 98,
      maxRecycleLoops: 99,
    },
    typicalSources: ['Auto repair shops', 'Battery retailers', 'Forklift operators', 'UPS systems'],
    endMarkets: ['Lead smelters', 'Battery manufacturers', 'Acid producers'],
    notes: 'Highest recycling rate of any product (>95%). Well-established infrastructure. Core deposit systems work.',
  },

  {
    id: '9.1.3-nimh-battery',
    class: 9,
    subclass: '9.1',
    sku: 'BATT-NIMH',
    tradeName: 'Nickel-Metal Hydride (NiMH) Batteries',
    alternativeNames: ['Hybrid car batteries', 'NiMH cells'],
    ewcCode: '16 06 02*',
    ewcDescription: 'nickel-cadmium batteries',
    wasteTier: 'T4',
    wasteTierDescription: 'Hazardous waste',
    hazard: {
      unNumber: 'UN 3496',
      adrClass: '9',
      packingGroup: 'II',
      hProperties: ['H14'],
      transportRestrictions: 'Class 9. Must be protected against short circuit.',
    },
    specifications: {
      composition: [
        { element: 'Nickel', range: { min: 30, max: 45 }, unit: '%' },
        { element: 'Rare earth metals (La, Ce)', range: { min: 15, max: 25 }, unit: '%' },
        { element: 'Iron', range: { min: 10, max: 20 }, unit: '%' },
        { element: 'Steel (case)', range: { min: 15, max: 25 }, unit: '%' },
      ],
      physicalForm: 'Battery packs, cells',
      bulkDensity: { min: 600, max: 800, unit: 'kg/mÂ³' },
    },
    pricing: {
      basePrice: 780,
      unit: 't',
      range: { min: 550, max: 1100 },
      marketIndex: 'LME',
      updateFrequency: 'daily',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Hybrid battery packs, intact, discharged', priceMultiplier: 1.25, contaminationMax: 5.0, certificationRequired: true },
      { tier: 'Q2', requirements: 'Standard NiMH batteries', priceMultiplier: 1.0, contaminationMax: 10.0, certificationRequired: true },
      { tier: 'Q3', requirements: 'Mixed battery types, consumer batteries', priceMultiplier: 0.70, contaminationMax: 20.0, certificationRequired: true },],
      processing: {
        recyclingRoutes: ['Nickel recovery', 'Rare earth recovery', 'Stainless steel production'],
      specialRequirements: 'Discharge before processing. Separate from other battery types.',
      difficulty: 'hard',
      energyRequired: 2.5,
      equipmentNeeded: ['Shredder', 'Magnetic separator', 'Hydrometallurgical processing'],
    },
    marketData: {
      demand: 'medium',
      supply: 'medium',
      volatility: 'medium',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 520,
      carbonAvoided: 4480,
      recyclabilityScore: 75,
      maxRecycleLoops: 99,
    },
    typicalSources: ['Hybrid vehicle dismantlers', 'Consumer electronics recycling'],
    endMarkets: ['Nickel recovery', 'Rare earth processing', 'Stainless steel mills'],
    notes: 'Declining market (replaced by Li-ion). Nickel + rare earth value. Hybrid vehicles main source.',
  },

  // 9.2 E-WASTE COMPONENTS - 6 SKUs
  {
    id: '9.2.1-pcb-high-grade',
    class: 9,
    subclass: '9.2',
    sku: 'EWASTE-PCB-HG',
    tradeName: 'High-Grade PCBs',
    alternativeNames: ['Computer motherboards', 'Server boards', 'Telecom boards'],
    ewcCode: '16 02 16',
    ewcDescription: 'components removed from discarded equipment other than those mentioned in 16 02 15',
    wasteTier: 'T3',
    wasteTierDescription: 'WEEE component - controlled waste',
    specifications: {
      composition: [
        { element: 'Copper', range: { min: 12, max: 25 }, unit: '%' },
        { element: 'Gold', range: { min: 0.01, max: 0.05 }, unit: '%' },
        { element: 'Silver', range: { min: 0.05, max: 0.2 }, unit: '%' },
        { element: 'Palladium', range: { min: 0.001, max: 0.01 }, unit: '%' },
        { element: 'Fiberglass/resin', range: { min: 40, max: 60 }, unit: '%' },
      ],
      physicalForm: 'Circuit boards',
      bulkDensity: { min: 400, max: 600, unit: 'kg/mÂ³' },
    },
    pricing: {
      basePrice: 3200,
      unit: 't',
      range: { min: 2400, max: 4500 },
      marketIndex: 'LME',
      updateFrequency: 'daily',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Server/telecom boards, high metal content, components intact', priceMultiplier: 1.45, contaminationMax: 5.0, certificationRequired: true },
      { tier: 'Q2', requirements: 'Computer motherboards, sorted', priceMultiplier: 1.0, contaminationMax: 10.0, certificationRequired: true },
      { tier: 'Q3', requirements: 'Mixed PCBs, lower grade', priceMultiplier: 0.65, contaminationMax: 20.0, certificationRequired: true },],
      processing: {
        recyclingRoutes: ['Smelting (precious metals)', 'Copper recovery', 'Hydrometallurgical processing'],
      specialRequirements: 'WEEE certification required. Brominated flame retardants (BFR) concern. Data destruction.',
      difficulty: 'hard',
      energyRequired: 4.2,
      equipmentNeeded: ['Shredder', 'Smelter', 'Refining equipment', 'BFR control'],
    },
    marketData: {
      demand: 'high',
      supply: 'medium',
      volatility: 'high',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 680,
      carbonAvoided: 15320,
      recyclabilityScore: 85,
      maxRecycleLoops: 99,
    },
    typicalSources: ['Data center decommissioning', 'IT asset disposition', 'Telecom equipment'],
    endMarkets: ['Precious metal refiners', 'Copper smelters', 'E-waste processors'],
    notes: 'High value from precious metals. Gold concentration higher than ore. BFR regulations tightening.',
  },

  {
    id: '9.2.2-pcb-low-grade',
    class: 9,
    subclass: '9.2',
    sku: 'EWASTE-PCB-LG',
    tradeName: 'Low-Grade PCBs',
    alternativeNames: ['TV boards', 'Appliance boards', 'Consumer electronics PCBs'],
    ewcCode: '16 02 16',
    ewcDescription: 'components removed from discarded equipment',
    wasteTier: 'T3',
    wasteTierDescription: 'WEEE component',
    specifications: {
      composition: [
        { element: 'Copper', range: { min: 8, max: 15 }, unit: '%' },
        { element: 'Gold', range: { min: 0.001, max: 0.01 }, unit: '%' },
        { element: 'Fiberglass/resin', range: { min: 60, max: 80 }, unit: '%' },
      ],
      physicalForm: 'Circuit boards',
      bulkDensity: { min: 350, max: 550, unit: 'kg/mÂ³' },
    },
    pricing: {
      basePrice: 850,
      unit: 't',
      range: { min: 550, max: 1300 },
      marketIndex: 'LME',
      updateFrequency: 'weekly',
    },
    qualityTiers: [
      { tier: 'Q2', requirements: 'Sorted by board type, clean', priceMultiplier: 1.25, contaminationMax: 10.0, certificationRequired: true },
      { tier: 'Q3', requirements: 'Mixed low-grade PCBs', priceMultiplier: 1.0, contaminationMax: 20.0, certificationRequired: true },
      { tier: 'Q4', requirements: 'Heavily contaminated, mixed materials', priceMultiplier: 0.60, contaminationMax: 35.0, certificationRequired: true },],
      processing: {
        recyclingRoutes: ['Copper recovery', 'Precious metal recovery', 'Energy recovery'],
      specialRequirements: 'Lower precious metal content. WEEE compliance.',
      difficulty: 'medium',
      energyRequired: 3.5,
      equipmentNeeded: ['Shredder', 'Separation equipment', 'Smelter'],
    },
    marketData: {
      demand: 'medium',
      supply: 'high',
      volatility: 'medium',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 720,
      carbonAvoided: 4280,
      recyclabilityScore: 70,
      maxRecycleLoops: 99,
    },
    typicalSources: ['Consumer electronics', 'Appliance recycling', 'TV/monitor dismantling'],
    endMarkets: ['Copper recovery', 'E-waste processors', 'Smelters'],
    notes: 'Lower value than high-grade. Copper main recovery target. Volume compensates for lower grade.',
  },

  {
    id: '9.2.3-cables-wire',
    class: 9,
    subclass: '9.2',
    sku: 'EWASTE-CABLE',
    tradeName: 'E-Waste Cables & Wire',
    alternativeNames: ['Insulated copper wire', 'Electronics cables'],
    ewcCode: '17 04 11',
    ewcDescription: 'cables other than those mentioned in 17 04 10',
    wasteTier: 'T2',
    wasteTierDescription: 'Non-hazardous e-waste component',
    specifications: {
      composition: [
        { element: 'Copper', range: { min: 40, max: 70 }, unit: '%' },
        { element: 'PVC insulation', range: { min: 25, max: 55 }, unit: '%' },
        { element: 'Other materials', range: { min: 3, max: 10 }, unit: '%' },
      ],
      physicalForm: 'Cables, wire',
      bulkDensity: { min: 400, max: 700, unit: 'kg/mÂ³' },
    },
    pricing: {
      basePrice: 1850,
      unit: 't',
      range: { min: 1200, max: 2600 },
      marketIndex: 'LME',
      updateFrequency: 'daily',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Thick copper wire, minimal insulation (<30%)', priceMultiplier: 1.40, contaminationMax: 5.0, certificationRequired: false },
      { tier: 'Q2', requirements: 'Standard cables, 40-60% copper', priceMultiplier: 1.0, contaminationMax: 15.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Thin wire, high insulation content', priceMultiplier: 0.60, contaminationMax: 30.0, certificationRequired: false },],
      processing: {
        recyclingRoutes: ['Granulation and separation', 'Pyrolysis', 'Export for processing'],
      specialRequirements: 'No burning (air pollution). Granulation preferred.',
      difficulty: 'easy',
      energyRequired: 0.8,
      equipmentNeeded: ['Wire granulator', 'Density separator', 'Magnetic separator'],
    },
    marketData: {
      demand: 'high',
      supply: 'high',
      volatility: 'medium',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 280,
      carbonAvoided: 4720,
      recyclabilityScore: 95,
      maxRecycleLoops: 99,
    },
    typicalSources: ['Electronics recycling', 'IT equipment dismantling', 'Construction demolition'],
    endMarkets: ['Copper recovery', 'Wire granulation facilities', 'Export'],
    notes: 'Good economics. Copper price-linked. Granulation technology mature. Avoid wire burning (illegal in most countries).',
  },

  {
    id: '9.2.4-lcd-screens',
    class: 9,
    subclass: '9.2',
    sku: 'EWASTE-LCD',
    tradeName: 'LCD Screens',
    alternativeNames: ['Flat panel displays', 'Computer monitors', 'TV screens'],
    ewcCode: '16 02 13*',
    ewcDescription: 'discarded equipment containing hazardous components',
    wasteTier: 'T4',
    wasteTierDescription: 'Hazardous - mercury in backlights (older models)',
    hazard: {
      unNumber: 'N/A',
      adrClass: undefined,
      packingGroup: undefined,
      hProperties: ['H14'],
      transportRestrictions: 'Check for mercury (pre-2011 screens). Handle as hazardous if Hg present.',
    },
    specifications: {
      composition: [
        { element: 'Glass', range: { min: 50, max: 70 }, unit: '%' },
        { element: 'Plastics', range: { min: 15, max: 25 }, unit: '%' },
        { element: 'Metals (Al, Cu)', range: { min: 5, max: 15 }, unit: '%' },
        { element: 'Indium (ITO)', range: { min: 0.001, max: 0.01 }, unit: '%' },
      ],
      physicalForm: 'Screens, panels',
      bulkDensity: { min: 300, max: 500, unit: 'kg/mÂ³' },
    },
    pricing: {
      basePrice: -12,
      unit: 't',
      range: { min: -45, max: 30 },
      marketIndex: undefined,
      updateFrequency: 'monthly',
    },
    qualityTiers: [
      { tier: 'Q2', requirements: 'LED-backlit (no Hg), intact, large format', priceMultiplier: 1.80, contaminationMax: 5.0, certificationRequired: true },
      { tier: 'Q3', requirements: 'Standard LCDs, Hg-free', priceMultiplier: 1.0, contaminationMax: 15.0, certificationRequired: true },
      { tier: 'Q4', requirements: 'CCFL backlight (Hg present), broken', priceMultiplier: 0.40, contaminationMax: 30.0, certificationRequired: true },],
      processing: {
        recyclingRoutes: ['Manual dismantling', 'Glass recovery', 'Indium recovery (advanced)', 'Hazardous waste disposal (if Hg)'],
      specialRequirements: 'Mercury removal for older CCFL backlights. Labor-intensive dismantling. Indium recovery emerging.',
      difficulty: 'very-hard',
      energyRequired: 1.5,
      equipmentNeeded: ['Dismantling line', 'Mercury capture (if CCFL)', 'Glass crusher'],
    },
    marketData: {
      demand: 'very-low',
      supply: 'very-high',
      volatility: 'low',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 420,
      carbonAvoided: 380,
      recyclabilityScore: 45,
      maxRecycleLoops: 1,
    },
    typicalSources: ['E-waste collection', 'Office equipment disposition', 'Consumer electronics'],
    endMarkets: ['Glass recovery', 'Hazardous waste disposal', 'Indium recovery (specialty)'],
    notes: 'Negative value typical - disposal cost. Mercury concern for pre-2011. Indium recovery not yet economical at scale.',
  },

  // 9.3 SOLAR PANELS - 3 SKUs
  {
    id: '9.3.1-solar-pv-silicon',
    class: 9,
    subclass: '9.3',
    sku: 'SOLAR-SI',
    tradeName: 'Silicon Solar Panels',
    alternativeNames: ['Crystalline silicon PV', 'End-of-life solar panels'],
    ewcCode: '16 02 14',
    ewcDescription: 'discarded equipment other than those mentioned in 16 02 09 to 16 02 13',
    wasteTier: 'T3',
    wasteTierDescription: 'WEEE - complex composite waste',
    specifications: {
      composition: [
        { element: 'Glass', range: { min: 70, max: 75 }, unit: '%' },
        { element: 'Silicon', range: { min: 3, max: 5 }, unit: '%' },
        { element: 'Aluminum (frame)', range: { min: 8, max: 12 }, unit: '%' },
        { element: 'Copper', range: { min: 1, max: 2 }, unit: '%' },
        { element: 'Silver', range: { min: 0.03, max: 0.05 }, unit: '%' },
        { element: 'Polymer (EVA, backsheet)', range: { min: 8, max: 12 }, unit: '%' },
      ],
      physicalForm: 'Panels',
      bulkDensity: { min: 100, max: 200, unit: 'kg/mÂ³' },
    },
    pricing: {
      basePrice: 35,
      unit: 't',
      range: { min: -15, max: 95 },
      marketIndex: undefined,
      updateFrequency: 'monthly',
    },
    qualityTiers: [
      { tier: 'Q2', requirements: 'Unbroken panels, frame intact, known manufacturer', priceMultiplier: 1.60, contaminationMax: 5.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Standard decommissioned panels', priceMultiplier: 1.0, contaminationMax: 15.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'Broken panels, mixed types', priceMultiplier: 0.50, contaminationMax: 30.0, certificationRequired: false },],
      processing: {
        recyclingRoutes: ['Thermal/chemical delamination', 'Glass recovery', 'Al frame recovery', 'Silicon recovery', 'Ag recovery'],
      specialRequirements: 'Delamination technology required. Labor intensive. Silver recovery adds value.',
      difficulty: 'hard',
      energyRequired: 2.8,
      equipmentNeeded: ['Delamination system', 'Crusher', 'Chemical processing'],
    },
    marketData: {
      demand: 'low',
      supply: 'low',
      volatility: 'medium',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 380,
      carbonAvoided: 1620,
      recyclabilityScore: 75,
      maxRecycleLoops: 1,
    },
    typicalSources: ['Solar farm decommissioning', 'Roof replacement', 'Hail damage', 'Manufacturing defects'],
    endMarkets: ['Panel recyclers', 'Glass recovery', 'Metal recovery', 'Emerging market for cells'],
    notes: 'Emerging waste stream (panels last 25-30yrs). EU WEEE directive applies. Infrastructure developing. Silver recovery key to economics.',
  },
];

export const ELECTRONICS_BATTERIES_CLASS: MaterialClass = {
  classNumber: 9,
  className: 'Electronics & Batteries',
  description: 'E-waste, batteries (Li-ion, lead-acid, NiMH), solar panels - hazardous and high-value',
  skuCount: 15,
  materials: ELECTRONICS_BATTERIES,
};

export default ELECTRONICS_BATTERIES;
