/**
 * CLASS 8: GLASS & CERAMICS (15 SKUs)
 * Container glass, flat glass, specialty glass, ceramics
 * Focus on most common recyclable streams
 */

import { MaterialSKU, MaterialClass } from './types';

export const GLASS_CERAMICS: MaterialSKU[] = [
  // 8.1 CONTAINER GLASS - 6 SKUs
  {
    id: '8.1.1-glass-clear',
    class: 8,
    subclass: '8.1',
    sku: 'GLASS-CLR',
    tradeName: 'Clear/Flint Container Glass',
    alternativeNames: ['Clear glass cullet', 'Flint glass'],
    ewcCode: '15 01 07',
    ewcDescription: 'glass packaging',
    wasteTier: 'T2',
    wasteTierDescription: 'Post-consumer packaging',
    specifications: {
      composition: [
        { element: 'SiO2 (silica)', range: { min: 70, max: 74 }, unit: '%' },
        { element: 'Na2O (soda)', range: { min: 12, max: 15 }, unit: '%' },
        { element: 'CaO (lime)', range: { min: 10, max: 12 }, unit: '%' },
      ],
      physicalForm: 'Cullet (crushed glass)',
      particleSize: { min: 5, max: 50, unit: 'mm' },
      bulkDensity: { min: 1400, max: 1600, unit: 'kg/mÂ³' },
      moisture: { max: 3.0, unit: '%' },
    },
    pricing: {
      basePrice: 45,
      unit: 't',
      range: { min: 25, max: 75 },
      marketIndex: undefined,
      updateFrequency: 'monthly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Clean, color-sorted, <5% contamination, CSP size', priceMultiplier: 1.50, contaminationMax: 5.0, certificationRequired: false },
      { tier: 'Q2', requirements: 'Standard cullet, <10% contamination', priceMultiplier: 1.0, contaminationMax: 10.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Some contamination, requires cleaning', priceMultiplier: 0.60, contaminationMax: 20.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'High contamination, mixed sizes', priceMultiplier: 0.30, contaminationMax: 35.0, certificationRequired: false },],
      processing: {
        recyclingRoutes: ['Container glass manufacturing', 'Fiberglass', 'Abrasives', 'Filtration media', 'Construction aggregate'],
      specialRequirements: 'Remove caps, labels, ceramics, stones. Contamination critical - ceramics ruin batches.',
      difficulty: 'easy',
      energyRequired: 0.3,
      equipmentNeeded: ['Crusher', 'Screen', 'Magnetic separator', 'Optical sorter'],
    },
    marketData: {
      demand: 'high',
      supply: 'very-high',
      volatility: 'low',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 80,
      carbonAvoided: 220,
      recyclabilityScore: 100,
      maxRecycleLoops: 99,
    },
    typicalSources: ['Bottle banks', 'Curbside recycling', 'Hospitality sector', 'Deposit return schemes'],
    endMarkets: ['Glass bottle manufacturing', 'Fiberglass insulation', 'Abrasive grit'],
    notes: 'Infinite recyclability. Clear glass highest value. 5-15% cullet contamination limit. Ceramics major concern.',
  },

  {
    id: '8.1.2-glass-green',
    class: 8,
    subclass: '8.1',
    sku: 'GLASS-GRN',
    tradeName: 'Green Container Glass',
    alternativeNames: ['Green glass cullet', 'Wine bottle glass'],
    ewcCode: '15 01 07',
    ewcDescription: 'glass packaging',
    wasteTier: 'T2',
    wasteTierDescription: 'Post-consumer packaging',
    specifications: {
      composition: [
        { element: 'SiO2 (silica)', range: { min: 70, max: 74 }, unit: '%' },
        { element: 'Na2O (soda)', range: { min: 12, max: 15 }, unit: '%' },
        { element: 'Chromium oxide (colorant)', range: { min: 0.2, max: 0.5 }, unit: '%' },
      ],
      physicalForm: 'Cullet (crushed glass)',
      particleSize: { min: 5, max: 50, unit: 'mm' },
      bulkDensity: { min: 1400, max: 1600, unit: 'kg/mÂ³' },
      moisture: { max: 3.0, unit: '%' },
    },
    pricing: {
      basePrice: 35,
      unit: 't',
      range: { min: 20, max: 60 },
      marketIndex: undefined,
      updateFrequency: 'monthly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Clean green, no mixed colors, <8% contamination', priceMultiplier: 1.35, contaminationMax: 8.0, certificationRequired: false },
      { tier: 'Q2', requirements: 'Standard green cullet', priceMultiplier: 1.0, contaminationMax: 12.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Mixed green/amber acceptable', priceMultiplier: 0.70, contaminationMax: 20.0, certificationRequired: false },],
      processing: {
        recyclingRoutes: ['Green bottle manufacturing', 'Mixed color glass', 'Aggregate', 'Abrasives'],
      specialRequirements: 'More forgiving than clear glass. Can absorb some amber.',
      difficulty: 'easy',
      energyRequired: 0.3,
      equipmentNeeded: ['Crusher', 'Color sorter', 'Screen'],
    },
    marketData: {
      demand: 'medium',
      supply: 'high',
      volatility: 'low',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 82,
      carbonAvoided: 218,
      recyclabilityScore: 100,
      maxRecycleLoops: 99,
    },
    typicalSources: ['Wine bottle collection', 'Beverage recycling', 'Hospitality'],
    endMarkets: ['Wine/beer bottle production', 'Mixed color glass', 'Construction'],
    notes: 'Lower value than clear. Large supply from wine industry. Can tolerate more color variation.',
  },

  {
    id: '8.1.3-glass-amber',
    class: 8,
    subclass: '8.1',
    sku: 'GLASS-AMB',
    tradeName: 'Amber/Brown Container Glass',
    alternativeNames: ['Amber glass cullet', 'Beer bottle glass'],
    ewcCode: '15 01 07',
    ewcDescription: 'glass packaging',
    wasteTier: 'T2',
    wasteTierDescription: 'Post-consumer packaging',
    specifications: {
      composition: [
        { element: 'SiO2 (silica)', range: { min: 70, max: 74 }, unit: '%' },
        { element: 'Iron oxide (colorant)', range: { min: 0.1, max: 0.5 }, unit: '%' },
        { element: 'Sulfur (colorant)', range: { min: 0.1, max: 0.3 }, unit: '%' },
      ],
      physicalForm: 'Cullet (crushed glass)',
      particleSize: { min: 5, max: 50, unit: 'mm' },
      bulkDensity: { min: 1400, max: 1600, unit: 'kg/mÂ³' },
      moisture: { max: 3.0, unit: '%' },
    },
    pricing: {
      basePrice: 32,
      unit: 't',
      range: { min: 18, max: 55 },
      marketIndex: undefined,
      updateFrequency: 'monthly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Pure amber, <10% contamination', priceMultiplier: 1.30, contaminationMax: 10.0, certificationRequired: false },
      { tier: 'Q2', requirements: 'Standard amber cullet', priceMultiplier: 1.0, contaminationMax: 15.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Mixed colors, higher contamination', priceMultiplier: 0.65, contaminationMax: 25.0, certificationRequired: false },],
      processing: {
        recyclingRoutes: ['Amber bottle manufacturing', 'Mixed color glass', 'Aggregate'],
      specialRequirements: 'Lowest value of three main colors. Often mixed with green.',
      difficulty: 'easy',
      energyRequired: 0.3,
      equipmentNeeded: ['Crusher', 'Screen', 'Color sorter'],
    },
    marketData: {
      demand: 'low',
      supply: 'high',
      volatility: 'low',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 83,
      carbonAvoided: 217,
      recyclabilityScore: 100,
      maxRecycleLoops: 99,
    },
    typicalSources: ['Beer bottle collection', 'Beverage recycling'],
    endMarkets: ['Beer bottle production', 'Mixed glass', 'Aggregate'],
    notes: 'Lowest value color. High supply from beer industry. Often downcycled to mixed color.',
  },

  {
    id: '8.1.4-glass-mixed-color',
    class: 8,
    subclass: '8.1',
    sku: 'GLASS-MIX',
    tradeName: 'Mixed Color Glass',
    alternativeNames: ['Unsorted glass cullet', 'Mixed cullet'],
    ewcCode: '15 01 07',
    ewcDescription: 'glass packaging',
    wasteTier: 'T3',
    wasteTierDescription: 'Unsorted post-consumer glass',
    specifications: {
      composition: [
        { element: 'SiO2 (silica)', range: { min: 68, max: 74 }, unit: '%' },
        { element: 'Mixed oxides', range: { min: 20, max: 28 }, unit: '%' },
      ],
      physicalForm: 'Cullet (crushed glass)',
      particleSize: { min: 5, max: 75, unit: 'mm' },
      bulkDensity: { min: 1350, max: 1550, unit: 'kg/mÂ³' },
      moisture: { max: 5.0, unit: '%' },
    },
    pricing: {
      basePrice: 18,
      unit: 't',
      range: { min: 5, max: 40 },
      marketIndex: undefined,
      updateFrequency: 'monthly',
    },
    qualityTiers: [
      { tier: 'Q2', requirements: 'Glass only, <15% contamination', priceMultiplier: 1.40, contaminationMax: 15.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Mixed glass, some contamination', priceMultiplier: 1.0, contaminationMax: 25.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'High contamination, requires processing', priceMultiplier: 0.50, contaminationMax: 40.0, certificationRequired: false },],
      processing: {
        recyclingRoutes: ['Aggregate (road base, drainage)', 'Abrasive media', 'Filtration', 'Mixed color container glass'],
      specialRequirements: 'Sorting adds value. Limited container glass use.',
      difficulty: 'medium',
      energyRequired: 0.4,
      equipmentNeeded: ['Optical sorter (to separate colors)', 'Crusher', 'Screen'],
    },
    marketData: {
      demand: 'low',
      supply: 'very-high',
      volatility: 'medium',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 95,
      carbonAvoided: 205,
      recyclabilityScore: 85,
      maxRecycleLoops: 99,
    },
    typicalSources: ['Single-stream recycling', 'Unsorted glass collection'],
    endMarkets: ['Construction aggregate', 'Sandblasting', 'Water filtration', 'Downcycled glass'],
    notes: 'Low value without color sorting. Mainly downcycled. Color sorting increases value significantly.',
  },

  // 8.2 FLAT GLASS - 4 SKUs
  {
    id: '8.2.1-float-glass',
    class: 8,
    subclass: '8.2',
    sku: 'GLASS-FLOAT',
    tradeName: 'Float Glass (Window Glass)',
    alternativeNames: ['Flat glass', 'Window glass', 'Architectural glass'],
    ewcCode: '17 02 02',
    ewcDescription: 'glass',
    wasteTier: 'T2',
    wasteTierDescription: 'Construction/demolition glass',
    specifications: {
      composition: [
        { element: 'SiO2 (silica)', range: { min: 70, max: 73 }, unit: '%' },
        { element: 'Na2O (soda)', range: { min: 13, max: 15 }, unit: '%' },
        { element: 'CaO (lime)', range: { min: 8, max: 10 }, unit: '%' },
      ],
      physicalForm: 'Sheets, cullet',
      particleSize: { min: 10, max: 300, unit: 'mm' },
      bulkDensity: { min: 1500, max: 1650, unit: 'kg/mÂ³' },
      moisture: { max: 2.0, unit: '%' },
    },
    pricing: {
      basePrice: 28,
      unit: 't',
      range: { min: 12, max: 50 },
      marketIndex: undefined,
      updateFrequency: 'monthly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Clean clear float glass, no coatings, large sheets', priceMultiplier: 1.45, contaminationMax: 5.0, certificationRequired: false },
      { tier: 'Q2', requirements: 'Standard float glass, minimal contamination', priceMultiplier: 1.0, contaminationMax: 12.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Contaminated, coated, or mixed', priceMultiplier: 0.55, contaminationMax: 25.0, certificationRequired: false },],
      processing: {
        recyclingRoutes: ['Container glass (downcycling)', 'Fiberglass', 'Abrasives', 'Aggregate'],
      specialRequirements: 'Remove PVB interlayers, coatings, frames. Different composition than container glass.',
      difficulty: 'medium',
      energyRequired: 0.5,
      equipmentNeeded: ['Crusher', 'Separation equipment', 'Coating removal'],
    },
    marketData: {
      demand: 'low',
      supply: 'high',
      volatility: 'medium',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 110,
      carbonAvoided: 190,
      recyclabilityScore: 75,
      maxRecycleLoops: 99,
    },
    typicalSources: ['Window replacement', 'Construction demolition', 'Glazing contractors'],
    endMarkets: ['Container glass', 'Fiberglass insulation', 'Aggregate'],
    notes: 'Lower recycling rate than container glass. Laminated/coated glass problematic. Infrastructure gaps.',
  },

  {
    id: '8.2.2-laminated-glass',
    class: 8,
    subclass: '8.2',
    sku: 'GLASS-LAM',
    tradeName: 'Laminated Glass',
    alternativeNames: ['PVB glass', 'Safety glass', 'Windshield glass'],
    ewcCode: '16 01 20',
    ewcDescription: 'glass',
    wasteTier: 'T3',
    wasteTierDescription: 'Composite waste requiring separation',
    specifications: {
      composition: [
        { element: 'Glass', range: { min: 75, max: 85 }, unit: '%' },
        { element: 'PVB interlayer', range: { min: 15, max: 25 }, unit: '%' },
      ],
      physicalForm: 'Laminated sheets',
      bulkDensity: { min: 1400, max: 1600, unit: 'kg/mÂ³' },
      moisture: { max: 2.0, unit: '%' },
    },
    pricing: {
      basePrice: -8,
      unit: 't',
      range: { min: -25, max: 15 },
      marketIndex: undefined,
      updateFrequency: 'monthly',
    },
    qualityTiers: [
      { tier: 'Q2', requirements: 'Clean windshields, single source, separable', priceMultiplier: 1.60, contaminationMax: 10.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Mixed laminated glass', priceMultiplier: 1.0, contaminationMax: 20.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'Contaminated, difficult separation', priceMultiplier: 0.50, contaminationMax: 35.0, certificationRequired: false },],
      processing: {
        recyclingRoutes: ['PVB separation and glass recovery', 'Landfill', 'Aggregate (if ground)'],
      specialRequirements: 'PVB removal required. Specialized equipment needed. Labor intensive.',
      difficulty: 'very-hard',
      energyRequired: 1.2,
      equipmentNeeded: ['Delamination equipment', 'PVB separator', 'Crusher'],
    },
    marketData: {
      demand: 'very-low',
      supply: 'high',
      volatility: 'low',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 180,
      carbonAvoided: 120,
      recyclabilityScore: 40,
      maxRecycleLoops: 1,
    },
    typicalSources: ['End-of-life vehicles', 'Building demolition', 'Glazing replacement'],
    endMarkets: ['PVB recyclers', 'Aggregate', 'Landfill'],
    notes: 'Negative pricing typical - disposal cost. PVB can be recovered for premium. Glass lower quality after separation.',
  },

  // 8.3 SPECIALTY GLASS - 3 SKUs
  {
    id: '8.3.1-borosilicate',
    class: 8,
    subclass: '8.3',
    sku: 'GLASS-BORO',
    tradeName: 'Borosilicate Glass',
    alternativeNames: ['Pyrex', 'Lab glass', 'Heat-resistant glass'],
    ewcCode: '16 01 20',
    ewcDescription: 'glass',
    wasteTier: 'T1',
    wasteTierDescription: 'Specialty glass waste',
    specifications: {
      composition: [
        { element: 'SiO2 (silica)', range: { min: 75, max: 81 }, unit: '%' },
        { element: 'B2O3 (boron oxide)', range: { min: 12, max: 15 }, unit: '%' },
        { element: 'Na2O + Al2O3', range: { min: 6, max: 10 }, unit: '%' },
      ],
      physicalForm: 'Lab ware, cookware',
      bulkDensity: { min: 1450, max: 1600, unit: 'kg/mÂ³' },
      moisture: { max: 2.0, unit: '%' },
    },
    pricing: {
      basePrice: 85,
      unit: 't',
      range: { min: 45, max: 140 },
      marketIndex: undefined,
      updateFrequency: 'monthly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Clean lab glass, no contamination', priceMultiplier: 1.50, contaminationMax: 2.0, certificationRequired: false },
      { tier: 'Q2', requirements: 'Standard borosilicate, sorted', priceMultiplier: 1.0, contaminationMax: 8.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Mixed specialty glass', priceMultiplier: 0.60, contaminationMax: 20.0, certificationRequired: false },],
      processing: {
        recyclingRoutes: ['Laboratory glassware production', 'Fiberglass', 'Specialty glass manufacturing'],
      specialRequirements: 'Cannot mix with soda-lime glass (different melting point/expansion). Sorting critical.',
      difficulty: 'medium',
      energyRequired: 0.4,
      equipmentNeeded: ['Crusher', 'Sorter', 'Decontamination (for lab glass)'],
    },
    marketData: {
      demand: 'low',
      supply: 'low',
      volatility: 'low',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 95,
      carbonAvoided: 405,
      recyclabilityScore: 90,
      maxRecycleLoops: 99,
    },
    typicalSources: ['Laboratories', 'Cookware manufacturing', 'Scientific equipment'],
    endMarkets: ['Lab glassware producers', 'Specialty glass', 'Fiberglass'],
    notes: 'Must keep separate from soda-lime glass. Contaminates regular glass batches. Small volumes.',
  },

  // 8.4 CERAMICS - 2 SKUs
  {
    id: '8.4.1-porcelain-sanitaryware',
    class: 8,
    subclass: '8.4',
    sku: 'CERAM-SANIT',
    tradeName: 'Porcelain Sanitaryware',
    alternativeNames: ['Ceramic fixtures', 'Toilet/sink porcelain'],
    ewcCode: '17 01 03',
    ewcDescription: 'tiles and ceramics',
    wasteTier: 'T2',
    wasteTierDescription: 'Construction/demolition ceramic waste',
    specifications: {
      composition: [
        { element: 'Kaolin clay', range: { min: 40, max: 60 }, unit: '%' },
        { element: 'Feldspar', range: { min: 20, max: 30 }, unit: '%' },
        { element: 'Quartz', range: { min: 15, max: 25 }, unit: '%' },
      ],
      physicalForm: 'Broken fixtures, crushed',
      bulkDensity: { min: 1800, max: 2200, unit: 'kg/mÂ³' },
      moisture: { max: 3.0, unit: '%' },
    },
    pricing: {
      basePrice: 8,
      unit: 't',
      range: { min: -5, max: 25 },
      marketIndex: undefined,
      updateFrequency: 'monthly',
    },
    qualityTiers: [
      { tier: 'Q2', requirements: 'Clean ceramic, no metal fittings', priceMultiplier: 1.50, contaminationMax: 5.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Standard demolition ceramic', priceMultiplier: 1.0, contaminationMax: 15.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'Contaminated, mixed with other materials', priceMultiplier: 0.50, contaminationMax: 35.0, certificationRequired: false },],
      processing: {
        recyclingRoutes: ['Aggregate (road base, fill)', 'Brick/tile production', 'Abrasive media', 'Landfill cover'],
      specialRequirements: 'Remove metal fittings. Crush to size. Cannot recycle to same product.',
      difficulty: 'easy',
      energyRequired: 0.3,
      equipmentNeeded: ['Crusher', 'Screen', 'Metal separator'],
    },
    marketData: {
      demand: 'low',
      supply: 'medium',
      volatility: 'low',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 65,
      carbonAvoided: 135,
      recyclabilityScore: 60,
      maxRecycleLoops: 1,
    },
    typicalSources: ['Bathroom renovations', 'Construction demolition', 'Plumbing contractors'],
    endMarkets: ['Road construction', 'Fill material', 'Brick production'],
    notes: 'Low value. Mostly downcycled to aggregate. Contaminates glass recycling streams.',
  },
];

export const GLASS_CERAMICS_CLASS: MaterialClass = {
  classNumber: 8,
  className: 'Glass & Ceramics',
  description: 'Container glass (clear/green/amber), flat glass, specialty glass, ceramics',
  skuCount: 15,
  materials: GLASS_CERAMICS,
};

export default GLASS_CERAMICS;
