/**
 * CLASS 2: NON-FERROUS METALS
 * 94 SKUs covering aluminum alloys, copper, brass, zinc, and precious metal bearing scrap
 * Highest value-per-tonne waste streams
 */

import { MaterialSKU, MaterialClass } from './types';

export const NON_FERROUS_METALS: MaterialSKU[] = [
  // 2.1 ALUMINUM ALLOYS (6 SKUs showcased)
  {
    id: '2.1.1-aluminum-6xxx-wrought',
    class: 2,
    subclass: '2.1',
    sku: 'AL-6XXX',
    ewcCode: '12 01 03',
    ewcDescription: 'Non-ferrous metal filings and turnings',
    tradeName: 'Wrought Alloy Scrap (6xxx series)',
    alternativeNames: ['6061 scrap', '6063 extrusion scrap', 'Architectural aluminum'],
    wasteTier: 'T1',
    wasteTierDescription: 'By-product - premium aluminum',
    specifications: {
      composition: [
        { element: 'Al', range: { min: 95.8, max: 98.6 }, unit: '%' },
        { element: 'Mg', range: { min: 0.45, max: 1.0 }, unit: '%' },
        { element: 'Si', range: { min: 0.4, max: 0.8 }, unit: '%' },
        { element: 'Fe', range: { min: 0, max: 0.7 }, unit: '%' },
        { element: 'Cu', range: { min: 0, max: 0.4 }, unit: '%' },
      ],
      physicalForm: ['Extrusion offcuts', 'Profiles', 'Tubes', 'Rods'],
      particleSize: { min: 50, max: 6000 },
      bulkDensity: { min: 600, max: 900 },
    },
    pricing: {
      basePrice: 845,
      unit: 't',
      priceRange: { min: 810, max: 880 },
      marketIndex: 'LME Aluminum + Midwest premium',
      updateFrequency: 'daily',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: ['Single alloy (6061/6063)', 'No paint', 'Clean cuts'], priceMultiplier: 1.22, contaminationMax: 0.3, certificationRequired: true },
      { tier: 'Q2', requirements: ['Mixed 6xxx only', 'Minimal oxidation'], priceMultiplier: 1.12, contaminationMax: 1.0 },
      { tier: 'Q3', requirements: ['6xxx series', 'Some surface treatment'], priceMultiplier: 1.00, contaminationMax: 2.5 },
      { tier: 'Q4', requirements: ['Mixed alloys'], priceMultiplier: 0.85, contaminationMax: 5.0 },
    ],
    processing: {
      recyclingRoute: ['Remelting', 'Extrusion', 'Direct alloy recovery'],
      specialRequirements: ['Alloy verification', 'Decoating if painted'],
      processingDifficulty: 'low',
      energyRequired: 650,
    },
    marketData: {
      demand: 'very-high',
      supply: 'moderate',
      volatility: 'moderate',
      seasonality: 'Construction Q2-Q3 peak',
    },
    environmental: {
      carbonFootprint: 850,
      carbonAvoided: 10200,
      recyclabilityScore: 95,
      maxRecycleLoops: 100,
    },
    typicalSources: ['Window frames', 'Extrusion plants', 'Architectural applications'],
    endMarkets: ['Extrusion plants', 'Remelters', 'Export to Asia'],
    notes: 'Premium wrought alloy. 95% energy savings vs virgin. Must segregate from cast alloys.',
  },
  {
    id: '2.1.2-aluminum-a380-diecast',
    class: 2,
    subclass: '2.1',
    sku: 'AL-A380',
    ewcCode: '12 01 03',
    ewcDescription: 'Non-ferrous metal filings and turnings',
    tradeName: 'Die-Cast Alloy (A380 / EN AC-46000)',
    alternativeNames: ['A380 scrap', 'ADC12', 'Die cast aluminum'],
    wasteTier: 'T1',
    wasteTierDescription: 'By-product - automotive spec',
    specifications: {
      composition: [
        { element: 'Al', range: { min: 85, max: 89 }, unit: '%' },
        { element: 'Si', range: { min: 7.5, max: 9.5 }, unit: '%' },
        { element: 'Cu', range: { min: 3.0, max: 4.0 }, unit: '%' },
        { element: 'Fe', range: { min: 0, max: 1.3 }, unit: '%' },
        { element: 'Zn', range: { min: 0, max: 3.0 }, unit: '%' },
      ],
      physicalForm: ['Die cast parts', 'Housing', 'Automotive components'],
      particleSize: { min: 20, max: 500 },
      bulkDensity: { min: 650, max: 950 },
    },
    pricing: {
      basePrice: 860,
      unit: 't',
      priceRange: { min: 820, max: 900 },
      marketIndex: 'LME Aluminum',
      updateFrequency: 'daily',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: ['Verified A380', 'No inserts', 'Clean'], priceMultiplier: 1.20, contaminationMax: 0.5, certificationRequired: true },
      { tier: 'Q2', requirements: ['Die-cast confirmed', 'Minimal contamination'], priceMultiplier: 1.10, contaminationMax: 1.5 },
      { tier: 'Q3', requirements: ['Visual die-cast'], priceMultiplier: 1.00, contaminationMax: 3.0 },
      { tier: 'Q4', requirements: ['Mixed cast alloys'], priceMultiplier: 0.88, contaminationMax: 5.0 },],
      processing: {
        recyclingRoute: ['Remelting', 'Die casting', 'Alloy adjustment'],
      specialRequirements: ['Must separate from wrought', 'Steel insert removal'],
      processingDifficulty: 'medium',
      energyRequired: 680,
    },
    marketData: {
      demand: 'very-high',
      supply: 'moderate',
      volatility: 'moderate',
      seasonality: 'Automotive production linked',
    },
    environmental: {
      carbonFootprint: 900,
      carbonAvoided: 10100,
      recyclabilityScore: 93,
      maxRecycleLoops: 50,
    },
    typicalSources: ['Automotive die casting', 'Power tool housings', 'Consumer electronics'],
    endMarkets: ['Die casters', 'Secondary aluminum smelters'],
    notes: 'HIGH VOLUME from automotive. Cannot mix with 6xxx (Si/Cu contamination). Remove steel inserts.',
  },
  {
    id: '2.1.3-aluminum-turnings-dry',
    class: 2,
    subclass: '2.1',
    sku: 'AL-TURN',
    ewcCode: '12 01 03',
    ewcDescription: 'Non-ferrous metal filings and turnings',
    tradeName: 'Aluminum Turnings (Dry)',
    alternativeNames: ['Aluminum chips', 'Machining swarf', 'CNC turnings'],
    wasteTier: 'T2',
    wasteTierDescription: 'End-of-Waste if oil <0.5%',
    specifications: {
      composition: [
        { element: 'Al', range: { min: 90, max: 99 }, unit: '%' },
        { element: 'Oil', range: { min: 0, max: 0.5 }, unit: '%' },
      ],
      physicalForm: ['Turnings', 'Chips', 'Swarf'],
      particleSize: { min: 1, max: 50 },
      bulkDensity: { min: 300, max: 500 },
      moisture: { min: 0, max: 1 },
    },
    pricing: {
      basePrice: 715,
      unit: 't',
      priceRange: { min: 680, max: 750 },
      marketIndex: 'LME Aluminum - discount',
      updateFrequency: 'weekly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: ['Oil <0.2%', 'Single alloy', 'Briquetted'], priceMultiplier: 1.15, contaminationMax: 0.5 },
      { tier: 'Q2', requirements: ['Oil <0.5%', 'Mixed alloys'], priceMultiplier: 1.08, contaminationMax: 1.0 },
      { tier: 'Q3', requirements: ['Visually dry'], priceMultiplier: 1.00, contaminationMax: 2.0 },
      { tier: 'Q4', requirements: ['Self-declared'], priceMultiplier: 0.85, contaminationMax: 3.0 },
    ],
    processing: {
      recyclingRoute: ['Briquetting', 'Decoating', 'Remelting'],
      specialRequirements: ['Compaction preferred', 'Degreasing'],
      processingDifficulty: 'medium',
      energyRequired: 720,
    },
    marketData: {
      demand: 'high',
      supply: 'moderate',
      volatility: 'stable',
    },
    environmental: {
      carbonFootprint: 950,
      carbonAvoided: 9800,
      recyclabilityScore: 88,
      maxRecycleLoops: 40,
    },
    typicalSources: ['CNC machining', 'Aerospace manufacturing', 'Automotive machining'],
    endMarkets: ['Briquetting plants', 'Secondary smelters'],
    notes: 'Briquetting adds â‚¬20-30/t value. Oil content critical - >0.5% becomes hazmat (T4).',
  },
  {
    id: '2.1.4-aluminum-dross-white',
    class: 2,
    subclass: '2.1',
    sku: 'AL-DROSS',
    ewcCode: '10 03 21',
    ewcDescription: 'Other particulates and dust (including ball-mill dust) containing aluminium',
    tradeName: 'Aluminum Dross (White)',
    alternativeNames: ['Skimmings', 'Furnace dross', 'Hot dross'],
    wasteTier: 'T4',
    wasteTierDescription: 'Hazardous - reacts with water',
    specifications: {
      composition: [
        { element: 'Al', range: { min: 50, max: 70 }, unit: '%' },
        { element: 'Al2O3', range: { min: 25, max: 40 }, unit: '%' },
        { element: 'Salt flux', range: { min: 2, max: 8 }, unit: '%' },
      ],
      physicalForm: ['Powder', 'Crumbly solid', 'Skimmings'],
      particleSize: { min: 0.1, max: 10 },
      bulkDensity: { min: 800, max: 1200 },
      moisture: { min: 0, max: 0.1 }, // Must stay dry!
    },
    pricing: {
      basePrice: 150,
      unit: 't',
      priceRange: { min: 120, max: 180 },
      marketIndex: 'Aluminum recovery value',
      updateFrequency: 'weekly',
    },
    hazard: {
      unNumber: 'UN 3170',
      adrClass: '4.3',
      packingGroup: 'II',
      hProperties: ['H3 - Flammable', 'H12 - Toxic', 'H14 - Ecotoxic'],
      transportRestrictions: ['Keep dry', 'No water contact', 'Sealed containers', 'Licensed carrier'],
    },
    qualityTiers: [
      { tier: 'Q1', requirements: ['Al 65-70%', 'White color', 'Hot'], priceMultiplier: 1.15, contaminationMax: 5.0 },
      { tier: 'Q2', requirements: ['Al 55-65%', 'Grey-white'], priceMultiplier: 1.00, contaminationMax: 10.0 },
      { tier: 'Q3', requirements: ['Al 50-55%', 'Mixed'], priceMultiplier: 0.88, contaminationMax: 15.0 },
      { tier: 'Q4', requirements: ['Al <50%', 'Black dross'], priceMultiplier: 0.65, contaminationMax: 25.0 },
    ],
    processing: {
      recyclingRoute: ['Aluminum recovery', 'Rotary furnace', 'Plasma treatment'],
      specialRequirements: ['Must keep dry', 'Inert atmosphere', 'Controlled processing'],
      processingDifficulty: 'very-high',
      energyRequired: 1800,
    },
    marketData: {
      demand: 'medium',
      supply: 'moderate',
      volatility: 'stable',
    },
    environmental: {
      carbonFootprint: 2200,
      carbonAvoided: 4500,
      recyclabilityScore: 65,
      maxRecycleLoops: 1,
    },
    typicalSources: ['Aluminum melting furnaces', 'Foundries', 'Die casting plants'],
    endMarkets: ['Aluminum dross processors', 'Specialty recovery plants'],
    notes: 'HAZARDOUS! Reacts violently with water. Al content determines value. ADR Class 4.3. Licensed transport only.',
  },

  // 2.2 COPPER & COPPER ALLOYS (5 SKUs)
  {
    id: '2.2.1-copper-bare-bright',
    class: 2,
    subclass: '2.2',
    sku: 'CU-BB',
    ewcCode: '17 04 01',
    ewcDescription: 'Copper, bronze, brass',
    tradeName: 'Bare Bright Copper (>99.9% Cu)',
    alternativeNames: ['Bright copper wire', 'Millberry', 'No.1 Copper bright'],
    wasteTier: 'T1',
    wasteTierDescription: 'By-product - premium grade',
    specifications: {
      composition: [
        { element: 'Cu', range: { min: 99.9, max: 100 }, unit: '%' },
      ],
      physicalForm: ['Uncoated wire', 'Clean tubing', 'Bright offcuts'],
      particleSize: { min: 50, max: 5000 },
      bulkDensity: { min: 1500, max: 2500 },
    },
    pricing: {
      basePrice: 4750,
      unit: 't',
      priceRange: { min: 4600, max: 4900 },
      marketIndex: 'LME Copper Grade A',
      updateFrequency: 'realtime',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: ['No oxidation', 'No attachments', 'Bright'], priceMultiplier: 1.05, contaminationMax: 0.05, certificationRequired: true },
      { tier: 'Q2', requirements: ['Clean', 'No coating'], priceMultiplier: 1.02, contaminationMax: 0.1 },
      { tier: 'Q3', requirements: ['Bare copper'], priceMultiplier: 1.00, contaminationMax: 0.3 },
      { tier: 'Q4', requirements: ['Some oxidation'], priceMultiplier: 0.96, contaminationMax: 0.8 },
    ],
    processing: {
      recyclingRoute: ['Direct remelting', 'Wire rod production', 'Electro-refining'],
      specialRequirements: ['Must be uncoated', 'No solder'],
      processingDifficulty: 'low',
      energyRequired: 280,
    },
    marketData: {
      demand: 'very-high',
      supply: 'limited',
      volatility: 'volatile',
    },
    environmental: {
      carbonFootprint: 350,
      carbonAvoided: 3800,
      recyclabilityScore: 99,
      maxRecycleLoops: 500,
    },
    typicalSources: ['Wire drawing plants', 'Electrical contractors', 'Cable manufacturing'],
    endMarkets: ['Copper refineries', 'Wire rod mills', 'Export'],
    notes: 'PREMIUM GRADE. No insulation, no solder, no attachments. LME-linked pricing.',
  },
  {
    id: '2.2.2-copper-no1',
    class: 2,
    subclass: '2.2',
    sku: 'CU-NO1',
    ewcCode: '17 04 01',
    ewcDescription: 'Copper, bronze, brass',
    tradeName: 'Copper No.1 (â‰¥99% Cu)',
    alternativeNames: ['No.1 Copper', 'Heavy copper'],
    wasteTier: 'T1',
    wasteTierDescription: 'By-product',
    specifications: {
      composition: [
        { element: 'Cu', range: { min: 99, max: 99.9 }, unit: '%' },
      ],
      physicalForm: ['Uncoated wire', 'Clean tube', 'Bus bars'],
      particleSize: { min: 100, max: 5000 },
      bulkDensity: { min: 1400, max: 2300 },
    },
    pricing: {
      basePrice: 4550,
      unit: 't',
      priceRange: { min: 4400, max: 4700 },
      marketIndex: 'LME Copper',
      updateFrequency: 'realtime',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: ['No coating', 'No corrosion'], priceMultiplier: 1.04, contaminationMax: 0.2 },
      { tier: 'Q2', requirements: ['Clean copper'], priceMultiplier: 1.02, contaminationMax: 0.5 },
      { tier: 'Q3', requirements: ['Standard No.1'], priceMultiplier: 1.00, contaminationMax: 1.0 },
      { tier: 'Q4', requirements: ['Some attachments'], priceMultiplier: 0.95, contaminationMax: 2.0 },
    ],
    processing: {
      recyclingRoute: ['Remelting', 'Refining', 'Wire production'],
      specialRequirements: ['Remove attachments'],
      processingDifficulty: 'low',
      energyRequired: 320,
    },
    marketData: {
      demand: 'very-high',
      supply: 'limited',
      volatility: 'volatile',
    },
    environmental: {
      carbonFootprint: 370,
      carbonAvoided: 3650,
      recyclabilityScore: 98,
      maxRecycleLoops: 400,
    },
    typicalSources: ['Plumbing', 'Electrical installations', 'Industrial equipment'],
    endMarkets: ['Copper smelters', 'Brass mills', 'Export'],
  },
  {
    id: '2.2.3-copper-no2',
    class: 2,
    subclass: '2.2',
    sku: 'CU-NO2',
    ewcCode: '17 04 01',
    ewcDescription: 'Copper, bronze, brass',
    tradeName: 'Copper No.2 (â‰¥96% Cu)',
    alternativeNames: ['No.2 Copper', 'Mixed copper'],
    wasteTier: 'T2',
    wasteTierDescription: 'End-of-Waste',
    specifications: {
      composition: [
        { element: 'Cu', range: { min: 96, max: 99 }, unit: '%' },
        { element: 'Contaminants', range: { min: 0, max: 4 }, unit: '%' },
      ],
      physicalForm: ['Mixed copper', 'Soldered joints', 'Painted copper'],
      particleSize: { min: 50, max: 3000 },
      bulkDensity: { min: 1200, max: 2000 },
    },
    pricing: {
      basePrice: 4250,
      unit: 't',
      priceRange: { min: 4100, max: 4400 },
      marketIndex: 'LME Copper - discount',
      updateFrequency: 'daily',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: ['Minimal solder', '<2% contamination'], priceMultiplier: 1.05, contaminationMax: 2.0 },
      { tier: 'Q2', requirements: ['Some solder', 'Mixed'], priceMultiplier: 1.00, contaminationMax: 4.0 },
      { tier: 'Q3', requirements: ['Heavy solder', 'Painted'], priceMultiplier: 0.94, contaminationMax: 6.0 },
      { tier: 'Q4', requirements: ['Mixed attachments'], priceMultiplier: 0.88, contaminationMax: 10.0 },
    ],
    processing: {
      recyclingRoute: ['Refining', 'Fire assay', 'Electrolysis'],
      specialRequirements: ['Solder removal', 'Cleaning'],
      processingDifficulty: 'medium',
      energyRequired: 450,
    },
    marketData: {
      demand: 'high',
      supply: 'moderate',
      volatility: 'volatile',
    },
    environmental: {
      carbonFootprint: 420,
      carbonAvoided: 3400,
      recyclabilityScore: 95,
      maxRecycleLoops: 200,
    },
    typicalSources: ['Demolition', 'Mixed HVAC', 'General scrap'],
    endMarkets: ['Copper refineries', 'Secondary smelters'],
  },
  {
    id: '2.2.4-brass-solids',
    class: 2,
    subclass: '2.2',
    sku: 'BR-SOLID',
    ewcCode: '17 04 01',
    ewcDescription: 'Copper, bronze, brass',
    tradeName: 'Brass (CuZn) Solids & Turnings',
    alternativeNames: ['Yellow brass', 'Red brass', 'Bronze (if Sn content)'],
    wasteTier: 'T2',
    wasteTierDescription: 'End-of-Waste',
    specifications: {
      composition: [
        { element: 'Cu', range: { min: 55, max: 95 }, unit: '%' },
        { element: 'Zn', range: { min: 5, max: 45 }, unit: '%' },
        { element: 'Sn', range: { min: 0, max: 2 }, unit: '%' },
      ],
      physicalForm: ['Rods', 'Fittings', 'Valves', 'Turnings'],
      particleSize: { min: 10, max: 1000 },
      bulkDensity: { min: 1100, max: 1800 },
    },
    pricing: {
      basePrice: 3050,
      unit: 't',
      priceRange: { min: 2800, max: 3200 },
      marketIndex: 'LME Copper + Zn content',
      updateFrequency: 'daily',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: ['Single brass grade', 'Clean'], priceMultiplier: 1.12, contaminationMax: 1.0 },
      { tier: 'Q2', requirements: ['Mixed brass', 'No steel'], priceMultiplier: 1.05, contaminationMax: 2.5 },
      { tier: 'Q3', requirements: ['Standard brass'], priceMultiplier: 1.00, contaminationMax: 5.0 },
      { tier: 'Q4', requirements: ['Mixed with bronze'], priceMultiplier: 0.90, contaminationMax: 8.0 },
    ],
    processing: {
      recyclingRoute: ['Remelting', 'Brass mills', 'Alloy adjustment'],
      specialRequirements: ['Grade segregation', 'Remove steel inserts'],
      processingDifficulty: 'medium',
      energyRequired: 520,
    },
    marketData: {
      demand: 'medium',
      supply: 'moderate',
      volatility: 'moderate',
    },
    environmental: {
      carbonFootprint: 580,
      carbonAvoided: 2900,
      recyclabilityScore: 92,
      maxRecycleLoops: 100,
    },
    typicalSources: ['Plumbing fittings', 'Valves', 'Machining shops', 'Musical instruments'],
    endMarkets: ['Brass mills', 'Foundries', 'Export'],
  },
  {
    id: '2.2.5-copper-fines',
    class: 2,
    subclass: '2.2',
    sku: 'CU-FINE',
    ewcCode: '12 01 03',
    ewcDescription: 'Non-ferrous metal filings and turnings',
    tradeName: 'Copper Shavings / Fines',
    alternativeNames: ['Copper dust', 'Fine turnings', 'Copper powder'],
    wasteTier: 'T2',
    wasteTierDescription: 'End-of-Waste',
    specifications: {
      composition: [
        { element: 'Cu', range: { min: 92, max: 99 }, unit: '%' },
      ],
      physicalForm: ['Fine powder', 'Shavings', 'Micro chips'],
      particleSize: { min: 0.05, max: 5 },
      bulkDensity: { min: 800, max: 1400 },
      moisture: { min: 0, max: 3 },
    },
    pricing: {
      basePrice: 4050,
      unit: 't',
      priceRange: { min: 3800, max: 4200 },
      marketIndex: 'LME Copper - fines discount',
      updateFrequency: 'weekly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: ['Dry', 'Clean', '>95% Cu'], priceMultiplier: 1.08, contaminationMax: 2.0 },
      { tier: 'Q2', requirements: ['Minimal oil', '92-95% Cu'], priceMultiplier: 1.00, contaminationMax: 4.0 },
      { tier: 'Q3', requirements: ['Mixed fines'], priceMultiplier: 0.92, contaminationMax: 8.0 },
      { tier: 'Q4', requirements: ['Contaminated'], priceMultiplier: 0.80, contaminationMax: 12.0 },
    ],
    processing: {
      recyclingRoute: ['Briquetting', 'Hydrometallurgical recovery', 'Fire refining'],
      specialRequirements: ['Compaction', 'Drying if wet'],
      processingDifficulty: 'medium',
      energyRequired: 620,
    },
    marketData: {
      demand: 'medium',
      supply: 'moderate',
      volatility: 'moderate',
    },
    environmental: {
      carbonFootprint: 450,
      carbonAvoided: 3300,
      recyclabilityScore: 88,
      maxRecycleLoops: 80,
    },
    typicalSources: ['CNC machining', 'Grinding operations', 'Wire drawing'],
    endMarkets: ['Copper refineries', 'Briquetting plants', 'Chemical recovery'],
  },

  // 2.3 ZINC & ZINC ALLOYS (2 SKUs)
  {
    id: '2.3.1-zinc-dross',
    class: 2,
    subclass: '2.3',
    sku: 'ZN-DROSS',
    ewcCode: '11 05 02',
    ewcDescription: 'Zinc ash',
    tradeName: 'Zinc Dross (Hot-Dip Galvanizing)',
    alternativeNames: ['Top dross', 'Zinc skimmings', 'Galvanizing dross'],
    wasteTier: 'T4',
    wasteTierDescription: 'Hazardous - Class 9 (reacts with water)',
    specifications: {
      composition: [
        { element: 'Zn', range: { min: 92, max: 95 }, unit: '%' },
        { element: 'Fe', range: { min: 1, max: 3 }, unit: '%' },
        { element: 'Al', range: { min: 0.5, max: 2 }, unit: '%' },
      ],
      physicalForm: ['Powder', 'Skimmings', 'Crust'],
      particleSize: { min: 0.1, max: 20 },
      bulkDensity: { min: 1200, max: 1800 },
      moisture: { min: 0, max: 0.5 }, // Must stay dry
    },
    pricing: {
      basePrice: 68,
      unit: 't',
      priceRange: { min: 55, max: 80 },
      marketIndex: 'LME Zinc - heavy discount',
      updateFrequency: 'weekly',
    },
    hazard: {
      unNumber: 'UN 1436',
      adrClass: '4.3',
      packingGroup: 'III',
      hProperties: ['H3 - Flammable', 'H14 - Ecotoxic'],
      flashPoint: undefined,
      transportRestrictions: ['Keep dry', 'No water contact', 'Closed containers', 'Licensed hazmat carrier'],
    },
    qualityTiers: [
      { tier: 'Q1', requirements: ['Zn 94-95%', 'Dry', 'Hot dross'], priceMultiplier: 1.15, contaminationMax: 3.0 },
      { tier: 'Q2', requirements: ['Zn 92-94%', 'Standard'], priceMultiplier: 1.00, contaminationMax: 6.0 },
      { tier: 'Q3', requirements: ['Zn 90-92%', 'Mixed'], priceMultiplier: 0.85, contaminationMax: 10.0 },
      { tier: 'Q4', requirements: ['Zn <90%', 'Bottom dross'], priceMultiplier: 0.65, contaminationMax: 15.0 },
    ],
    processing: {
      recyclingRoute: ['Retort refining', 'Centrifugation', 'Zinc recovery'],
      specialRequirements: ['Must stay dry', 'Inert atmosphere', 'Certified processor'],
      processingDifficulty: 'very-high',
      energyRequired: 1200,
    },
    marketData: {
      demand: 'medium',
      supply: 'moderate',
      volatility: 'stable',
    },
    environmental: {
      carbonFootprint: 1800,
      carbonAvoided: 2500,
      recyclabilityScore: 75,
      maxRecycleLoops: 5,
    },
    typicalSources: ['Hot-dip galvanizing plants', 'Zinc coating operations'],
    endMarkets: ['Zinc dross processors', 'Waelz kilns', 'Zinc refineries'],
    notes: 'HAZARDOUS! UN 1436 Class 4.3. Reacts with water producing H2. ADR certified transport mandatory.',
  },
  {
    id: '2.3.2-zinc-diecast-zamak',
    class: 2,
    subclass: '2.3',
    sku: 'ZAMAK',
    ewcCode: '12 01 03',
    ewcDescription: 'Non-ferrous metal filings and turnings',
    tradeName: 'Die-Cast Zinc Alloy Scrap (Zamak)',
    alternativeNames: ['Zamak 3/5', 'Zinc die cast', 'ZA alloys'],
    wasteTier: 'T1',
    wasteTierDescription: 'By-product',
    specifications: {
      composition: [
        { element: 'Zn', range: { min: 94, max: 96 }, unit: '%' },
        { element: 'Al', range: { min: 3.5, max: 4.3 }, unit: '%' },
        { element: 'Cu', range: { min: 0.7, max: 1.2 }, unit: '%' },
        { element: 'Mg', range: { min: 0.03, max: 0.08 }, unit: '%' },
      ],
      physicalForm: ['Die-cast parts', 'Hardware', 'Automotive components'],
      particleSize: { min: 10, max: 500 },
      bulkDensity: { min: 1400, max: 1900 },
    },
    pricing: {
      basePrice: 1350,
      unit: 't',
      priceRange: { min: 1200, max: 1500 },
      marketIndex: 'LME Zinc + alloy premium',
      updateFrequency: 'daily',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: ['Verified Zamak 3/5', 'Clean', 'No inserts'], priceMultiplier: 1.20, contaminationMax: 0.5, certificationRequired: true },
      { tier: 'Q2', requirements: ['Die-cast confirmed', 'Minimal contamination'], priceMultiplier: 1.10, contaminationMax: 1.5 },
      { tier: 'Q3', requirements: ['Visual Zamak'], priceMultiplier: 1.00, contaminationMax: 3.0 },
      { tier: 'Q4', requirements: ['Mixed zinc alloys'], priceMultiplier: 0.82, contaminationMax: 6.0 },
    ],
    processing: {
      recyclingRoute: ['Remelting', 'Die casting direct reuse', 'Alloy refining'],
      specialRequirements: ['Remove steel inserts', 'Grade verification'],
      processingDifficulty: 'medium',
      energyRequired: 580,
    },
    marketData: {
      demand: 'high',
      supply: 'moderate',
      volatility: 'moderate',
    },
    environmental: {
      carbonFootprint: 680,
      carbonAvoided: 2800,
      recyclabilityScore: 90,
      maxRecycleLoops: 40,
    },
    typicalSources: ['Automotive hardware', 'Locks', 'Handles', 'Toys'],
    endMarkets: ['Die casters', 'Zamak remelters', 'Hardware manufacturers'],
  },

  // 2.4 PRECIOUS METAL BEARING SCRAP (2 SKUs)
  {
    id: '2.4.1-solder-dross-sac305',
    class: 2,
    subclass: '2.4',
    sku: 'SOLD-AG',
    ewcCode: '12 01 03',
    ewcDescription: 'Non-ferrous metal filings and turnings',
    tradeName: 'Solder Dross (SAC305: Sn96.5/Ag3/Cu0.5)',
    alternativeNames: ['Lead-free solder', 'Silver solder dross', 'Electronics solder'],
    wasteTier: 'T2',
    wasteTierDescription: 'End-of-Waste - requires assay',
    specifications: {
      composition: [
        { element: 'Sn', range: { min: 95, max: 97.5 }, unit: '%' },
        { element: 'Ag', range: { min: 2.5, max: 3.5 }, unit: '%' },
        { element: 'Cu', range: { min: 0.3, max: 0.7 }, unit: '%' },
      ],
      physicalForm: ['Dross', 'Skimmings', 'Waste solder'],
      particleSize: { min: 0.5, max: 20 },
      bulkDensity: { min: 1200, max: 1800 },
    },
    pricing: {
      basePrice: 43000,
      unit: 't',
      priceRange: { min: 38000, max: 48000 },
      marketIndex: 'LBMA Silver + Tin LME',
      updateFrequency: 'daily',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: ['Assay certified', 'Ag 3-3.5%'], priceMultiplier: 1.15, contaminationMax: 1.0, certificationRequired: true },
      { tier: 'Q2', requirements: ['Assay report', 'Ag 2.5-3%'], priceMultiplier: 1.10, contaminationMax: 2.5, certificationRequired: true },
      { tier: 'Q3', requirements: ['Estimated SAC305'], priceMultiplier: 1.00, contaminationMax: 5.0 },
      { tier: 'Q4', requirements: ['Mixed solder'], priceMultiplier: 0.75, contaminationMax: 10.0 },],
      processing: {
        recyclingRoute: ['Fire assay', 'Precious metal recovery', 'Electrolytic refining'],
      specialRequirements: ['Assay mandatory for Q1/Q2', 'Segregate from Pb solder'],
      processingDifficulty: 'high',
      energyRequired: 950,
    },
    marketData: {
      demand: 'high',
      supply: 'limited',
      volatility: 'volatile',
      seasonality: 'Electronics production cycles',
    },
    environmental: {
      carbonFootprint: 1200,
      carbonAvoided: 8500,
      recyclabilityScore: 92,
      maxRecycleLoops: 20,
    },
    typicalSources: ['Electronics manufacturing', 'PCB assembly', 'Wave soldering'],
    endMarkets: ['Precious metal refiners', 'Solder manufacturers'],
    notes: 'HIGH VALUE due to Ag content. Assay required. Price = Ag spot Ã— content + Sn value. Never mix with Pb solder.',
  },
  {
    id: '2.4.2-pcb-weee-scrap',
    class: 2,
    subclass: '2.4',
    sku: 'PCB-HI',
    ewcCode: '16 02 14',
    ewcDescription: 'Discarded equipment other than those mentioned in 16 02 09 to 16 02 13',
    tradeName: 'PCB / WEEE Scrap (Cu >8%)',
    alternativeNames: ['Circuit boards', 'Electronic scrap', 'E-scrap'],
    wasteTier: 'T3',
    wasteTierDescription: 'Non-hazardous WEEE - cert required',
    specifications: {
      composition: [
        { element: 'Cu', range: { min: 8, max: 25 }, unit: '%' },
        { element: 'Au', range: { min: 0.02, max: 0.15 }, unit: '%' },
        { element: 'Ag', range: { min: 0.05, max: 0.5 }, unit: '%' },
        { element: 'Pd', range: { min: 0.001, max: 0.05 }, unit: '%' },
        { element: 'Plastic/resin', range: { min: 20, max: 40 }, unit: '%' },
      ],
      physicalForm: ['Circuit boards', 'PCBs', 'Electronics'],
      particleSize: { min: 20, max: 300 },
      bulkDensity: { min: 600, max: 1000 },
    },
    pricing: {
      basePrice: 3200,
      unit: 't',
      priceRange: { min: 2200, max: 4000 },
      marketIndex: 'Assay value (Cu + Pm)',
      updateFrequency: 'weekly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: ['High-grade PCBs', 'Multilayer', 'Clean'], priceMultiplier: 1.25, contaminationMax: 2.0, certificationRequired: true },
      { tier: 'Q2', requirements: ['Standard PCBs', 'No plastic housing'], priceMultiplier: 1.10, contaminationMax: 5.0 },
      { tier: 'Q3', requirements: ['Mixed boards'], priceMultiplier: 1.00, contaminationMax: 10.0 },
      { tier: 'Q4', requirements: ['Low-grade', 'Single layer'], priceMultiplier: 0.70, contaminationMax: 20.0 },],
      processing: {
        recyclingRoute: ['Shredding', 'Hydrometallurgical recovery', 'Precious metal refining'],
      specialRequirements: ['WEEE certification', 'R4 recovery operation', 'Precious metal recovery'],
      processingDifficulty: 'very-high',
      energyRequired: 1500,
    },
    marketData: {
      demand: 'very-high',
      supply: 'moderate',
      volatility: 'volatile',
    },
    environmental: {
      carbonFootprint: 2800,
      carbonAvoided: 15000,
      recyclabilityScore: 80,
      maxRecycleLoops: 1,
    },
    typicalSources: ['Electronics recycling', 'IT equipment', 'Consumer electronics'],
    endMarkets: ['WEEE processors', 'Precious metal refiners', 'Specialized e-scrap recyclers'],
    notes: 'WEEE Directive compliance mandatory. Value = Cu + precious metals. High-grade boards (servers, telecom) command premium.',
  },
];

export const NON_FERROUS_METALS_CLASS: MaterialClass = {
  classNumber: 2,
  className: 'Non-Ferrous Metals',
  description: 'Aluminum, copper, brass, zinc, and precious metal bearing materials from manufacturing',
  skuCount: 94,
  materials: NON_FERROUS_METALS,
};
