/**
 * CLASS 5: ORGANIC WASTE (25 SKUs - Most Common)
 * Food processing waste, wood, paper/cardboard, agricultural residues
 * Focus on materials with anaerobic digestion, composting, or energy recovery potential
 */

import { MaterialSKU, MaterialClass } from './types';

export const ORGANICS: MaterialSKU[] = [
  // 5.1 FOOD PROCESSING WASTE - 8 SKUs
  {
    id: '5.1.1-food-oil-fats',
    class: 5,
    subclass: '5.1',
    sku: 'ORG-FOG',
    tradeName: 'Fats, Oils, and Grease (FOG)',
    alternativeNames: ['Used cooking oil', 'Trap grease', 'Yellow grease'],
    ewcCode: '02 02 03',
   ewcDescription: 'materials unsuitable for consumption or processing',
    wasteTier: 'T2',
    wasteTierDescription: 'Organic waste suitable for recovery',
    specifications: {
      composition: [
        { element: 'Triglycerides (fats/oils)', range: { min: 85, max: 100 }, unit: '%' },
        { element: 'Free fatty acids', range: { min: 0, max: 15 }, unit: '%' },
      ],
      physicalForm: 'Liquid or semi-solid',
      bulkDensity: { min: 900, max: 950, unit: 'kg/mÂ³' },
      moisture: { max: 5.0, unit: '%' },
    },
    pricing: {
      basePrice: 185,
      unit: 't',
      range: { min: 120, max: 280 },
      marketIndex: 'OPIS',
      updateFrequency: 'weekly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Clean cooking oil, low FFA (<3%), food-service source', priceMultiplier: 1.40, contaminationMax: 2.0, certificationRequired: false },
      { tier: 'Q2', requirements: 'Standard yellow grease, FFA 3-10%', priceMultiplier: 1.0, contaminationMax: 5.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Trap grease, FFA 10-15%, needs processing', priceMultiplier: 0.60, contaminationMax: 15.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'Brown grease, high water/solids content', priceMultiplier: 0.35, contaminationMax: 30.0, certificationRequired: false },
    ],
    processing: {
      recyclingRoutes: ['Biodiesel production', 'Renewable diesel', 'Anaerobic digestion', 'Animal feed (if food-grade)'],
      specialRequirements: 'Remove water and solids. Test for PCBs if industrial source.',
      difficulty: 'easy',
      energyRequired: 0.8,
      equipmentNeeded: ['Centrifuge', 'Heating/dewatering', 'Storage tanks'],
    },
    marketData: {
      demand: 'very-high',
      supply: 'high',
      volatility: 'high',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 420,
      carbonAvoided: 2080,
      recyclabilityScore: 95,
      maxRecycleLoops: 99,
    },
    typicalSources: ['Restaurants', 'Food processing plants', 'Grease traps', 'Industrial fryers'],
    endMarkets: ['Biodiesel producers', 'Renewable diesel refineries', 'Animal feed', 'Biogas plants'],
    notes: 'High-demand feedstock for biofuels. Pricing linked to diesel/RIN credits. FFA content affects value.',
  },

  {
    id: '5.1.2-fruit-pomace',
    class: 5,
    subclass: '5.1',
    sku: 'ORG-POMACE',
    tradeName: 'Fruit Pomace',
    alternativeNames: ['Apple pomace', 'Grape pomace', 'Berry pulp'],
    ewcCode: '02 03 01',
    ewcDescription: 'sludges from washing, cleaning, peeling, centrifuging and separation',
    wasteTier: 'T1',
    wasteTierDescription: 'By-product from processing',
    specifications: {
      composition: [
        { element: 'Fruit fiber (cellulose/pectin)', range: { min: 40, max: 70 }, unit: '%' },
        { element: 'Sugars/starch', range: { min: 10, max: 30 }, unit: '%' },
        { element: 'Moisture', range: { min: 15, max: 50 }, unit: '%' },
      ],
      physicalForm: 'Wet pulp',
      bulkDensity: { min: 500, max: 700, unit: 'kg/mÂ³' },
      moisture: { max: 65.0, unit: '%' },
    },
    pricing: {
      basePrice: 15,
      unit: 't',
      range: { min: -10, max: 45 },
      marketIndex: undefined,
      updateFrequency: 'monthly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Fresh pomace (<24hrs), single fruit type, no additives', priceMultiplier: 1.60, contaminationMax: 1.0, certificationRequired: false },
      { tier: 'Q2', requirements: 'Fresh pomace, identifiable source', priceMultiplier: 1.0, contaminationMax: 5.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Aged pomace, some fermentation', priceMultiplier: 0.50, contaminationMax: 15.0, certificationRequired: false },
    ],
    processing: {
      recyclingRoutes: ['Animal feed (cattle/pig)', 'Anaerobic digestion', 'Composting', 'Pectin extraction'],
      specialRequirements: 'Must be used quickly or ensiled. High moisture causes spoilage.',
      difficulty: 'easy',
      energyRequired: 0.3,
      equipmentNeeded: ['Pressing equipment', 'Drying (optional)', 'Mixing'],
    },
    marketData: {
      demand: 'medium',
      supply: 'high',
      volatility: 'low',
      seasonality: true,
    },
    environmental: {
      carbonFootprint: 80,
      carbonAvoided: 450,
      recyclabilityScore: 85,
      maxRecycleLoops: 1,
    },
    typicalSources: ['Juice production', 'Wineries', 'Cider mills', 'Fruit processing'],
    endMarkets: ['Animal feed', 'Biogas production', 'Compost', 'Pectin producers'],
    notes: 'Seasonal availability (harvest). Must find outlet quickly due to spoilage. Good biogas substrate.',
  },

  {
    id: '5.1.3-brewery-spent-grain',
    class: 5,
    subclass: '5.1',
    sku: 'ORG-BSG',
    tradeName: 'Brewery Spent Grain (BSG)',
    alternativeNames: ['Brewer\'s grain', 'Draff', 'Malt residue'],
    ewcCode: '02 07 01',
    ewcDescription: 'wastes from washing, cleaning and mechanical reduction of raw materials',
    wasteTier: 'T1',
    wasteTierDescription: 'By-product from brewing',
    specifications: {
      composition: [
        { element: 'Fiber (cellulose/hemicellulose)', range: { min: 50, max: 70 }, unit: '% dry' },
        { element: 'Protein', range: { min: 20, max: 30 }, unit: '% dry' },
        { element: 'Moisture', range: { min: 70, max: 80 }, unit: '%' },
      ],
      physicalForm: 'Wet grain',
      bulkDensity: { min: 1000, max: 1100, unit: 'kg/mÂ³' },
      moisture: { max: 80.0, unit: '%' },
    },
    pricing: {
      basePrice: 8,
      unit: 't',
      range: { min: -15, max: 35 },
      marketIndex: undefined,
      updateFrequency: 'monthly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Fresh (<48hrs), consistent barley source, no hops contamination', priceMultiplier: 1.50, contaminationMax: 1.0, certificationRequired: false },
      { tier: 'Q2', requirements: 'Standard BSG, fresh', priceMultiplier: 1.0, contaminationMax: 5.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Aged BSG, minor spoilage', priceMultiplier: 0.40, contaminationMax: 15.0, certificationRequired: false },],
      processing: {
        recyclingRoutes: ['Cattle feed (wet or dried)', 'Anaerobic digestion', 'Composting', 'Protein extraction'],
      specialRequirements: 'Short shelf-life (2-3 days). Ensiling or drying required for storage.',
      difficulty: 'easy',
      energyRequired: 0.5,
      equipmentNeeded: ['Screw press (dewatering)', 'Drier (optional)', 'Storage bins'],
    },
    marketData: {
      demand: 'high',
      supply: 'high',
      volatility: 'low',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 60,
      carbonAvoided: 380,
      recyclabilityScore: 90,
      maxRecycleLoops: 1,
    },
    typicalSources: ['Breweries', 'Distilleries', 'Malting operations'],
    endMarkets: ['Dairy farms', 'Beef cattle', 'Biogas plants', 'Protein extraction'],
    notes: 'Abundant from breweries. High protein content. Logistics challenge due to high moisture and spoilage.',
  },

  {
    id: '5.1.4-whey-permeate',
    class: 5,
    subclass: '5.1',
    sku: 'ORG-WHEY-PERM',
    tradeName: 'Whey Permeate/Lactose',
    alternativeNames: ['Dairy waste', 'Deproteinized whey'],
    ewcCode: '02 05 01',
    ewcDescription: 'materials unsuitable for consumption or processing',
    wasteTier: 'T3',
    wasteTierDescription: 'Organic wastewater requiring treatment',
    specifications: {
      composition: [
        { element: 'Lactose', range: { min: 70, max: 90 }, unit: '% dry' },
        { element: 'Ash/minerals', range: { min: 8, max: 15 }, unit: '% dry' },
        { element: 'Moisture', range: { min: 90, max: 96 }, unit: '%' },
      ],
      physicalForm: 'Liquid',
      bulkDensity: { min: 1020, max: 1050, unit: 'kg/mÂ³' },
      moisture: { max: 96.0, unit: '%' },
    },
    pricing: {
      basePrice: -8,
      unit: 't',
      range: { min: -35, max: 20 },
      marketIndex: undefined,
      updateFrequency: 'monthly',
    },
    qualityTiers: [
      { tier: 'Q2', requirements: 'High lactose content (>80% dry), low BOD', priceMultiplier: 1.80, contaminationMax: 5.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Standard permeate, suitable for AD', priceMultiplier: 1.0, contaminationMax: 15.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'Dilute or contaminated', priceMultiplier: 0.50, contaminationMax: 30.0, certificationRequired: false },],
      processing: {
        recyclingRoutes: ['Anaerobic digestion (high biogas yield)', 'Animal feed (pig)', 'Land application', 'Evaporation/spray drying'],
      specialRequirements: 'High BOD/COD - must treat or dilute. Acidic pH.',
      difficulty: 'medium',
      energyRequired: 2.5,
      equipmentNeeded: ['Anaerobic digester', 'Evaporator', 'pH control'],
    },
    marketData: {
      demand: 'low',
      supply: 'medium',
      volatility: 'low',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 150,
      carbonAvoided: 850,
      recyclabilityScore: 70,
      maxRecycleLoops: 1,
    },
    typicalSources: ['Cheese production', 'Whey protein manufacturing', 'Dairy processing'],
    endMarkets: ['Biogas production', 'Pig feed supplement', 'Wastewater treatment'],
    notes: 'Disposal challenge for dairy. Excellent biogas substrate (high methane yield). Negative pricing typical.',
  },

  // 5.2 WOOD & FIBER - 8 SKUs
  {
    id: '5.2.1-wood-chips-clean',
    class: 5,
    subclass: '5.2',
    sku: 'ORG-WOOD-CHP',
    tradeName: 'Clean Wood Chips',
    alternativeNames: ['Virgin wood chips', 'Forestry residue'],
    ewcCode: '03 01 01',
    ewcDescription: 'waste bark and cork',
    wasteTier: 'T1',
    wasteTierDescription: 'By-product from forestry/sawmills',
    specifications: {
      composition: [
        { element: 'Wood (cellulose/lignin)', range: { min: 95, max: 100 }, unit: '%' },
      ],
      physicalForm: 'Chips',
      particleSize: { min: 10, max: 50, unit: 'mm' },
      bulkDensity: { min: 250, max: 400, unit: 'kg/mÂ³' },
      moisture: { max: 50.0, unit: '%' },
    },
    pricing: {
      basePrice: 35,
      unit: 't',
      range: { min: 15, max: 65 },
      marketIndex: undefined,
      updateFrequency: 'monthly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Low moisture (<30%), no bark, softwood', priceMultiplier: 1.50, contaminationMax: 1.0, certificationRequired: false },
      { tier: 'Q2', requirements: 'Standard chips, <40% moisture', priceMultiplier: 1.0, contaminationMax: 5.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Mixed species, higher moisture', priceMultiplier: 0.70, contaminationMax: 15.0, certificationRequired: false },
    ],
    processing: {
      recyclingRoutes: ['Energy (biomass combustion)', 'Pulp/paper', 'Particleboard', 'Animal bedding', 'Biochar'],
      specialRequirements: 'Drying required for energy use. No treated wood.',
      difficulty: 'easy',
      energyRequired: 0.4,
      equipmentNeeded: ['Chipper', 'Dryer', 'Screener'],
    },
    marketData: {
      demand: 'high',
      supply: 'very-high',
      volatility: 'low',
      seasonality: true,
    },
    environmental: {
      carbonFootprint: 50,
      carbonAvoided: 1350,
      recyclabilityScore: 85,
      maxRecycleLoops: 1,
    },
    typicalSources: ['Sawmills', 'Logging operations', 'Land clearing', 'Tree trimming'],
    endMarkets: ['Biomass power plants', 'Paper mills', 'Particleboard', 'Biochar producers'],
    notes: 'Seasonal availability. Moisture content critical for energy applications. Transportation costs dominate economics.',
  },

  {
    id: '5.2.2-sawdust',
    class: 5,
    subclass: '5.2',
    sku: 'ORG-SAWDUST',
    tradeName: 'Sawdust',
    alternativeNames: ['Wood dust', 'Wood flour'],
    ewcCode: '03 01 05',
    ewcDescription: 'sawdust, shavings, cuttings, wood, particle board and veneer other than those mentioned in 03 01 04',
    wasteTier: 'T1',
    wasteTierDescription: 'By-product from woodworking',
    specifications: {
      composition: [
        { element: 'Wood fiber', range: { min: 98, max: 100 }, unit: '%' },
      ],
      physicalForm: 'Fine powder',
      particleSize: { min: 0.1, max: 3, unit: 'mm' },
      bulkDensity: { min: 150, max: 250, unit: 'kg/mÂ³' },
      moisture: { max: 20.0, unit: '%' },
    },
    pricing: {
      basePrice: 25,
      unit: 't',
      range: { min: 5, max: 55 },
      marketIndex: undefined,
      updateFrequency: 'monthly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Hardwood, dry (<12% moisture), no contamination', priceMultiplier: 1.60, contaminationMax: 0.5, certificationRequired: false },
      { tier: 'Q2', requirements: 'Clean sawdust, softwood acceptable', priceMultiplier: 1.0, contaminationMax: 3.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Mixed species, some bark acceptable', priceMultiplier: 0.65, contaminationMax: 10.0, certificationRequired: false },
    ],
    processing: {
      recyclingRoutes: ['Wood pellets', 'Animal bedding', 'Composting bulking agent', 'Absorbent', 'Wood-plastic composites'],
      specialRequirements: 'Dust explosion hazard - requires ventilation and spark control.',
      difficulty: 'easy',
      energyRequired: 0.2,
      equipmentNeeded: ['Pellet mill (optional)', 'Bagger', 'Dust collection'],
    },
    marketData: {
      demand: 'medium',
      supply: 'very-high',
      volatility: 'low',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 40,
      carbonAvoided: 420,
      recyclabilityScore: 80,
      maxRecycleLoops: 1,
    },
    typicalSources: ['Sawmills', 'Carpentry workshops', 'Furniture manufacturing'],
    endMarkets: ['Animal bedding (horses/poultry)', 'Pellet production', 'Compost bulking'],
    notes: 'Low bulk density makes transport expensive. Local markets preferred. Hardwood commands premium.',
  },

  {
    id: '5.2.3-cardboard-occ',
    class: 5,
    subclass: '5.2',
    sku: 'ORG-OCC',
    tradeName: 'Old Corrugated Containers (OCC)',
    alternativeNames: ['Cardboard bales', 'Corrugated boxes'],
    ewcCode: '15 01 01',
    ewcDescription: 'paper and cardboard packaging',
    wasteTier: 'T2',
    wasteTierDescription: 'Post-consumer/commercial packaging',
    specifications: {
      composition: [
        { element: 'Corrugated cardboard', range: { min: 90, max: 100 }, unit: '%' },
      ],
      physicalForm: 'Baled',
      bulkDensity: { min: 400, max: 650, unit: 'kg/mÂ³' },
      moisture: { max: 12.0, unit: '%' },
    },
    pricing: {
      basePrice: 110,
      unit: 't',
      range: { min: 40, max: 180 },
      marketIndex: undefined,
      updateFrequency: 'monthly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Clean post-industrial, dry, kraft liner quality', priceMultiplier: 1.35, contaminationMax: 2.0, certificationRequired: false },
      { tier: 'Q2', requirements: 'Standard OCC, <5% contamination', priceMultiplier: 1.0, contaminationMax: 5.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Contaminated OCC, wet acceptable if dried', priceMultiplier: 0.60, contaminationMax: 15.0, certificationRequired: false },
    ],
    processing: {
      recyclingRoutes: ['Pulping and paper recycling', 'Molded fiber products', 'Animal bedding'],
      specialRequirements: 'Remove plastic tape, staples. Keep dry (moisture penalty).',
      difficulty: 'easy',
      energyRequired: 1.2,
      equipmentNeeded: ['Baler', 'Pulper', 'Screening'],
    },
    marketData: {
      demand: 'very-high',
      supply: 'very-high',
      volatility: 'high',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 180,
      carbonAvoided: 1320,
      recyclabilityScore: 85,
      maxRecycleLoops: 7,
    },
    typicalSources: ['Retail stores', 'Distribution centers', 'E-commerce', 'Manufacturing'],
    endMarkets: ['Containerboard mills', 'Molded fiber packaging', 'Animal bedding'],
    notes: 'Commodity material - pricing highly volatile based on Chinese demand. Contamination severely penalized.',
  },

  {
    id: '5.2.4-paper-mixed',
    class: 5,
    subclass: '5.2',
    sku: 'ORG-PAPER-MIX',
    tradeName: 'Mixed Paper',
    alternativeNames: ['Office paper', 'Sorted office paper', 'White ledger'],
    ewcCode: '15 01 01',
    ewcDescription: 'paper and cardboard packaging',
    wasteTier: 'T2',
    wasteTierDescription: 'Post-consumer paper',
    specifications: {
      composition: [
        { element: 'Paper fiber', range: { min: 85, max: 100 }, unit: '%' },
      ],
      physicalForm: 'Baled sheets',
      bulkDensity: { min: 500, max: 700, unit: 'kg/mÂ³' },
      moisture: { max: 10.0, unit: '%' },
    },
    pricing: {
      basePrice: 85,
      unit: 't',
      range: { min: 20, max: 150 },
      marketIndex: undefined,
      updateFrequency: 'monthly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'White office paper, no glossy/coated, single-source', priceMultiplier: 1.50, contaminationMax: 2.0, certificationRequired: false },
      { tier: 'Q2', requirements: 'Mixed office paper, minimal colored stock', priceMultiplier: 1.0, contaminationMax: 8.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Contaminated mixed paper', priceMultiplier: 0.50, contaminationMax: 20.0, certificationRequired: false },],
      processing: {
        recyclingRoutes: ['Pulping and paper recycling', 'Tissue manufacturing', 'Newsprint'],
      specialRequirements: 'Remove plastic windows from envelopes. Avoid wet/moldy paper.',
      difficulty: 'easy',
      energyRequired: 1.0,
      equipmentNeeded: ['Baler', 'Pulper', 'De-inking (for white paper)'],
    },
    marketData: {
      demand: 'high',
      supply: 'high',
      volatility: 'medium',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 220,
      carbonAvoided: 1580,
      recyclabilityScore: 80,
      maxRecycleLoops: 6,
    },
    typicalSources: ['Offices', 'Schools', 'Print shops', 'Mail sorting facilities'],
    endMarkets: ['Tissue mills', 'Newsprint mills', 'Paperboard'],
    notes: 'White office paper commands premium. Colored/glossy paper lower value. De-inking costly.',
  },

  // 5.3 AGRICULTURAL RESIDUES - 5 SKUs
  {
    id: '5.3.1-straw',
    class: 5,
    subclass: '5.3',
    sku: 'ORG-STRAW',
    tradeName: 'Cereal Straw',
    alternativeNames: ['Wheat straw', 'Rice straw', 'Barley straw'],
    ewcCode: '02 01 03',
    ewcDescription: 'plant-tissue waste',
    wasteTier: 'T1',
    wasteTierDescription: 'Agricultural by-product',
    specifications: {
      composition: [
        { element: 'Cellulose', range: { min: 35, max: 45 }, unit: '%' },
        { element: 'Lignin', range: { min: 15, max: 25 }, unit: '%' },
        { element: 'Hemicellulose', range: { min: 20, max: 30 }, unit: '%' },
      ],
      physicalForm: 'Baled',
      bulkDensity: { min: 100, max: 150, unit: 'kg/mÂ³' },
      moisture: { max: 20.0, unit: '%' },
    },
    pricing: {
      basePrice: 45,
      unit: 't',
      range: { min: 20, max: 85 },
      marketIndex: undefined,
      updateFrequency: 'monthly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Wheat straw, dry (<15% moisture), no mold', priceMultiplier: 1.40, contaminationMax: 2.0, certificationRequired: false },
      { tier: 'Q2', requirements: 'Clean straw, standard moisture', priceMultiplier: 1.0, contaminationMax: 8.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Mixed cereal straw, some weathering', priceMultiplier: 0.60, contaminationMax: 20.0, certificationRequired: false },],
      processing: {
        recyclingRoutes: ['Animal bedding', 'Biomass energy', 'Bioethanol (2nd gen)', 'Pulping', 'Mushroom substrate', 'Biochar'],
      specialRequirements: 'Must be baled for transport. Keep dry to prevent combustion.',
      difficulty: 'easy',
      energyRequired: 0.3,
      equipmentNeeded: ['Baler', 'Chopper'],
    },
    marketData: {
      demand: 'medium',
      supply: 'very-high',
      volatility: 'medium',
      seasonality: true,
    },
    environmental: {
      carbonFootprint: 35,
      carbonAvoided: 1265,
      recyclabilityScore: 75,
      maxRecycleLoops: 1,
    },
    typicalSources: ['Grain harvesting', 'Rice paddies', 'Cereal farms'],
    endMarkets: ['Animal bedding', 'Biomass power', 'Cellulosic ethanol', 'Pulp mills'],
    notes: 'Seasonal (harvest). Low bulk density = high transport costs. Wheat straw preferred for industrial uses.',
  },

  {
    id: '5.3.2-corn-stover',
    class: 5,
    subclass: '5.3',
    sku: 'ORG-STOVER',
    tradeName: 'Corn Stover',
    alternativeNames: ['Maize stalks', 'Corn residue'],
    ewcCode: '02 01 03',
    ewcDescription: 'plant-tissue waste',
    wasteTier: 'T1',
    wasteTierDescription: 'Agricultural residue',
    specifications: {
      composition: [
        { element: 'Cellulose', range: { min: 35, max: 40 }, unit: '%' },
        { element: 'Hemicellulose', range: { min: 20, max: 25 }, unit: '%' },
        { element: 'Lignin', range: { min: 15, max: 20 }, unit: '%' },
      ],
      physicalForm: 'Baled or chopped',
      bulkDensity: { min: 120, max: 180, unit: 'kg/mÂ³' },
      moisture: { max: 25.0, unit: '%' },
    },
    pricing: {
      basePrice: 38,
      unit: 't',
      range: { min: 15, max: 70 },
      marketIndex: undefined,
      updateFrequency: 'monthly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Baled, dry (<18% moisture), no soil contamination', priceMultiplier: 1.35, contaminationMax: 3.0, certificationRequired: false },
      { tier: 'Q2', requirements: 'Standard stover, some cob acceptable', priceMultiplier: 1.0, contaminationMax: 10.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'High soil content or weathered', priceMultiplier: 0.55, contaminationMax: 25.0, certificationRequired: false },],
      processing: {
        recyclingRoutes: ['Cellulosic ethanol', 'Biomass energy', 'Animal feed (low quality)', 'Biochar'],
      specialRequirements: 'Soil contamination reduces value. Ash content critical for energy use.',
      difficulty: 'medium',
      energyRequired: 0.4,
      equipmentNeeded: ['Baler', 'Grinder'],
    },
    marketData: {
      demand: 'low',
      supply: 'very-high',
      volatility: 'low',
      seasonality: true,
    },
    environmental: {
      carbonFootprint: 40,
      carbonAvoided: 1160,
      recyclabilityScore: 70,
      maxRecycleLoops: 1,
    },
    typicalSources: ['Corn farms', 'Grain harvesting'],
    endMarkets: ['Cellulosic ethanol plants', 'Biomass power', 'Biochar'],
    notes: 'Large potential volume but low value. Soil health concerns limit removal. Cellulosic ethanol main driver.',
  },

  // 5.4 COMPOST FEEDSTOCKS - 4 SKUs
  {
    id: '5.4.1-yard-waste',
    class: 5,
    subclass: '5.4',
    sku: 'ORG-YARD',
    tradeName: 'Yard Waste',
    alternativeNames: ['Green waste', 'Grass clippings', 'Leaves'],
    ewcCode: '20 02 01',
    ewcDescription: 'biodegradable waste',
    wasteTier: 'T2',
    wasteTierDescription: 'Municipal organic waste',
    specifications: {
      composition: [
        { element: 'Mixed plant material', range: { min: 90, max: 100 }, unit: '%' },
      ],
      physicalForm: 'Loose or bagged',
      bulkDensity: { min: 250, max: 450, unit: 'kg/mÂ³' },
      moisture: { max: 60.0, unit: '%' },
    },
    pricing: {
      basePrice: -5,
      unit: 't',
      range: { min: -25, max: 15 },
      marketIndex: undefined,
      updateFrequency: 'monthly',
    },
    qualityTiers: [
      { tier: 'Q2', requirements: 'Clean yard waste, no contamination', priceMultiplier: 1.40, contaminationMax: 2.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Standard mixed yard waste', priceMultiplier: 1.0, contaminationMax: 10.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'Contaminated with trash/plastic bags', priceMultiplier: 0.50, contaminationMax: 25.0, certificationRequired: false },],
      processing: {
        recyclingRoutes: ['Composting', 'Mulch production', 'Anaerobic digestion'],
      specialRequirements: 'Remove plastic bags and trash. Grind woody material.',
      difficulty: 'easy',
      energyRequired: 0.2,
      equipmentNeeded: ['Grinder', 'Screener', 'Compost turner'],
    },
    marketData: {
      demand: 'medium',
      supply: 'very-high',
      volatility: 'low',
      seasonality: true,
    },
    environmental: {
      carbonFootprint: 25,
      carbonAvoided: 675,
      recyclabilityScore: 80,
      maxRecycleLoops: 1,
    },
    typicalSources: ['Residential collection', 'Landscaping services', 'Parks maintenance'],
    endMarkets: ['Compost products', 'Mulch', 'Biogas (if contaminant-free)'],
    notes: 'Seasonal peaks (spring/fall). Contamination with plastic major issue. Often requires tipping fee.',
  },
];

export const ORGANICS_CLASS: MaterialClass = {
  classNumber: 5,
  className: 'Organic Waste',
  description: 'Food processing, wood, paper, agricultural residues - no liquid waste',
  skuCount: 25,
  materials: ORGANICS,
};

export default ORGANICS;
