/**
 * CLASS 3: POLYMERS & PLASTICS (112 SKUs)
 * Thermoplastics, engineering plastics, contaminated streams, regrind
 * Post-industrial (T1) and post-consumer (T2/T3)
 */

import { MaterialSKU, MaterialClass } from './types';

export const POLYMERS: MaterialSKU[] = [
  // 3.1 POLYPROPYLENE (PP) - 18 SKUs
  {
    id: '3.1.1-pp-sprues-runners',
    class: 3,
    subclass: '3.1',
    sku: 'POLY-PP-SPRUES',
    tradeName: 'PP Sprues & Runners',
    alternativeNames: ['PP Regrind', 'PP Post-Industrial', 'PP Virgin-Like'],
    ewcCode: '12 01 05',
    ewcDescription: 'plastics shavings and turnings',
    wasteTier: 'T1',
    wasteTierDescription: 'By-product from injection molding',
    specifications: {
      composition: [
        { element: 'Polypropylene homopolymer', range: { min: 99, max: 100 }, unit: '%' },
      ],
      physicalForm: 'Sprues, runners, small regrind',
      particleSize: { min: 5, max: 50, unit: 'mm' },
      bulkDensity: { min: 450, max: 550, unit: 'kg/mÂ³' },
      moisture: { max: 0.1, unit: '%' },
    },
    pricing: {
      basePrice: 520,
      unit: 't',
      range: { min: 450, max: 580 },
      marketIndex: 'ICIS',
      updateFrequency: 'weekly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Single Resin - PP homopolymer only, colorless/natural, no contamination', priceMultiplier: 1.15, contaminationMax: 0.2, certificationRequired: true },
      { tier: 'Q2', requirements: 'Single grade - one color acceptable, <0.5% other plastics', priceMultiplier: 1.0, contaminationMax: 0.5, certificationRequired: false },
      { tier: 'Q3', requirements: 'Mixed PP grades, multiple colors acceptable', priceMultiplier: 0.85, contaminationMax: 1.5, certificationRequired: false },
      { tier: 'Q4', requirements: 'PP with minor PE/PS contamination', priceMultiplier: 0.65, contaminationMax: 5.0, certificationRequired: false },
    ],
    processing: {
      recyclingRoutes: ['Mechanical recycling', 'Re-extrusion', 'Compounding'],
      specialRequirements: 'Grind to <10mm if needed, wash if dirty',
      difficulty: 'easy',
      energyRequired: 2.1,
      equipmentNeeded: ['Granulator', 'Wash line (if contaminated)', 'Extrusion line'],
    },
    marketData: {
      demand: 'high',
      supply: 'medium',
      volatility: 'low',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 250,
      carbonAvoided: 1740,
      recyclabilityScore: 95,
      maxRecycleLoops: 5,
    },
    typicalSources: ['Injection molding plants', 'Automotive suppliers', 'Packaging manufacturers'],
    endMarkets: ['Automotive interior parts', 'Household goods', 'Industrial containers'],
    notes: 'Excellent feedstock for recycling. Virgin-like quality if single resin natural color.',
  },
  {
    id: '3.1.2-pp-colored',
    class: 3,
    subclass: '3.1',
    sku: 'POLY-PP-COLOR',
    tradeName: 'PP Colored Regrind',
    alternativeNames: ['PP Mixed Colors'],
    ewcCode: '12 01 05',
    ewcDescription: 'plastics shavings and turnings',
    wasteTier: 'T1',
    wasteTierDescription: 'Post-industrial colored material',
    specifications: {
      composition: [
        { element: 'Polypropylene', range: { min: 98, max: 100 }, unit: '%' },
      ],
      physicalForm: 'Regrind',
      particleSize: { min: 5, max: 50, unit: 'mm' },
      bulkDensity: { min: 450, max: 550, unit: 'kg/mÂ³' },
      moisture: { max: 0.2, unit: '%' },
    },
    pricing: {
      basePrice: 380,
      unit: 't',
      range: { min: 320, max: 450 },
      marketIndex: 'ICIS',
      updateFrequency: 'weekly',
    },
    qualityTiers: [
      { tier: 'Q2', requirements: 'Single color, clean', priceMultiplier: 1.10, contaminationMax: 0.5, certificationRequired: false },
      { tier: 'Q3', requirements: 'Mixed colors', priceMultiplier: 1.0, contaminationMax: 2.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'Multiple colors, some contamination', priceMultiplier: 0.75, contaminationMax: 5.0, certificationRequired: false },
    ],
    processing: {
      recyclingRoutes: ['Mechanical recycling', 'Compounding'],
      specialRequirements: 'Color sorting recommended for better value',
      difficulty: 'easy',
      energyRequired: 2.1,
      equipmentNeeded: ['Granulator', 'Color sorter', 'Extruder'],
    },
    marketData: {
      demand: 'high',
      supply: 'high',
      volatility: 'low',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 260,
      carbonAvoided: 1730,
      recyclabilityScore: 90,
      maxRecycleLoops: 5,
    },
    typicalSources: ['Automotive parts', 'Consumer goods', 'Packaging'],
    endMarkets: ['Non-critical parts', 'Storage containers', 'Pallets'],
    notes: 'Lower value than natural but still highly recyclable.',
  },

  {
    id: '3.1.3-pp-raffia',
    class: 3,
    subclass: '3.1',
    sku: 'POLY-PP-RAFF',
    tradeName: 'PP Raffia/Big Bags',
    alternativeNames: ['PP woven sacks', 'FIBC scrap', 'Jumbo bags'],
    ewcCode: '15 01 02',
    ewcDescription: 'plastic packaging',
    wasteTier: 'T2',
    wasteTierDescription: 'Post-consumer packaging',
    specifications: {
      composition: [
        { element: 'Polypropylene', range: { min: 95, max: 99 }, unit: '%' },
      ],
      physicalForm: 'Woven fabric, baled',
      particleSize: { min: 100, max: 500, unit: 'mm' },
      bulkDensity: { min: 200, max: 350, unit: 'kg/mÂ³' },
      moisture: { max: 1.5, unit: '%' },
    },
    pricing: {
      basePrice: 290,
      unit: 't',
      range: { min: 220, max: 380 },
      marketIndex: 'ICIS',
      updateFrequency: 'weekly',
    },
    qualityTiers: [
      { tier: 'Q2', requirements: 'Clean industrial bags, no printing', priceMultiplier: 1.15, contaminationMax: 2.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Standard used bags, clean', priceMultiplier: 1.0, contaminationMax: 5.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'Contaminated bags, heavy printing', priceMultiplier: 0.70, contaminationMax: 12.0, certificationRequired: false },
    ],
    processing: {
      recyclingRoutes: ['Shredding and washing', 'Pelletizing'],
      specialRequirements: 'Remove metal clips, wash printed surfaces',
      difficulty: 'medium',
      energyRequired: 2.5,
      equipmentNeeded: ['Shredder', 'Wash line', 'Extruder'],
    },
    marketData: {
      demand: 'medium',
      supply: 'high',
      volatility: 'medium',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 310,
      carbonAvoided: 1680,
      recyclabilityScore: 80,
      maxRecycleLoops: 4,
    },
    typicalSources: ['Chemical industry', 'Agriculture', 'Construction materials'],
    endMarkets: ['New woven bags', 'Pallets', 'Automotive parts'],
    notes: 'Large volume stream from industrial packaging.',
  },

  // 3.2 ABS (ACRYLONITRILE BUTADIENE STYRENE) - 2 SKUs
  {
    id: '3.2.1-abs-natural',
    class: 3,
    subclass: '3.2',
    sku: 'POLY-ABS-NAT',
    tradeName: 'ABS Natural Post-Industrial',
    alternativeNames: ['ABS Virgin Regrind', 'ABS Sprues'],
    ewcCode: '12 01 05',
    ewcDescription: 'plastics shavings and turnings',
    wasteTier: 'T1',
    wasteTierDescription: 'By-product from injection molding',
    specifications: {
      composition: [
        { element: 'Acrylonitrile', range: { min: 20, max: 25 }, unit: '%' },
        { element: 'Butadiene', range: { min: 23, max: 28 }, unit: '%' },
        { element: 'Styrene', range: { min: 50, max: 55 }, unit: '%' },
      ],
      physicalForm: 'Regrind, sprues, runners',
      particleSize: { min: 3, max: 15, unit: 'mm' },
      bulkDensity: { min: 550, max: 650, unit: 'kg/mÂ³' },
      moisture: { max: 0.1, unit: '%' },
    },
    pricing: {
      basePrice: 950,
      unit: 't',
      range: { min: 850, max: 1100 },
      marketIndex: 'ICIS',
      updateFrequency: 'weekly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Natural/light color, single grade (e.g., ABS 757), no flame retardant', priceMultiplier: 1.20, contaminationMax: 0.1, certificationRequired: true },
      { tier: 'Q2', requirements: 'Single color, known grade, <0.5% other plastics', priceMultiplier: 1.0, contaminationMax: 0.5, certificationRequired: false },
      { tier: 'Q3', requirements: 'Mixed colors acceptable, ABS only', priceMultiplier: 0.80, contaminationMax: 2.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'Mixed ABS grades, some contamination', priceMultiplier: 0.60, contaminationMax: 5.0, certificationRequired: false },
    ],
    processing: {
      recyclingRoutes: ['Mechanical recycling', 'Re-extrusion', 'Compounding with virgin ABS'],
      specialRequirements: 'Avoid mixing with PC-ABS blends. Check for brominated flame retardants (BFR).',
      difficulty: 'medium',
      energyRequired: 2.8,
      equipmentNeeded: ['Granulator', 'Drying equipment (120Â°C, 3hrs)', 'Twin-screw extruder'],
    },
    marketData: {
      demand: 'high',
      supply: 'medium',
      volatility: 'medium',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 380,
      carbonAvoided: 2920,
      recyclabilityScore: 85,
      maxRecycleLoops: 4,
    },
    typicalSources: ['Electronics assembly', 'Automotive trim molders', 'Appliance manufacturers'],
    endMarkets: ['Automotive interior', 'Electronics housings', 'Appliances'],
    notes: 'Higher value engineering plastic. Drying is critical before reprocessing.',
  },

  // 3.3 POLYETHYLENE (PE) - 6 SKUs
  {
    id: '3.3.1-hdpe-natural',
    class: 3,
    subclass: '3.3',
    sku: 'POLY-HDPE-NAT',
    tradeName: 'HDPE Natural Post-Industrial',
    alternativeNames: ['HDPE Regrind', 'PE-HD'],
    ewcCode: '12 01 05',
    ewcDescription: 'plastics shavings and turnings',
    wasteTier: 'T1',
    wasteTierDescription: 'By-product from blow molding',
    specifications: {
      composition: [
        { element: 'High-density polyethylene', range: { min: 99, max: 100 }, unit: '%' },
      ],
      physicalForm: 'Regrind, flake, baled film',
      particleSize: { min: 5, max: 20, unit: 'mm' },
      bulkDensity: { min: 500, max: 600, unit: 'kg/mÂ³' },
      moisture: { max: 0.2, unit: '%' },
    },
    pricing: {
      basePrice: 480,
      unit: 't',
      range: { min: 400, max: 550 },
      marketIndex: 'ICIS',
      updateFrequency: 'weekly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Natural/white color, single grade (e.g., HM5502), blow molding grade', priceMultiplier: 1.12, contaminationMax: 0.3, certificationRequired: true },
      { tier: 'Q2', requirements: 'Single color, <1% LDPE, clean', priceMultiplier: 1.0, contaminationMax: 1.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Mixed colors, HDPE only', priceMultiplier: 0.82, contaminationMax: 2.5, certificationRequired: false },
      { tier: 'Q4', requirements: 'Mixed PE (HDPE + some LDPE)', priceMultiplier: 0.65, contaminationMax: 8.0, certificationRequired: false },
    ],
    processing: {
      recyclingRoutes: ['Mechanical recycling', 'Film production', 'Blow molding applications'],
      specialRequirements: 'Separate from LDPE if possible for best quality',
      difficulty: 'easy',
      energyRequired: 1.9,
      equipmentNeeded: ['Granulator', 'Wash line', 'Extrusion line'],
    },
    marketData: {
      demand: 'very-high',
      supply: 'high',
      volatility: 'low',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 220,
      carbonAvoided: 1670,
      recyclabilityScore: 92,
      maxRecycleLoops: 6,
    },
    typicalSources: ['Bottle manufacturing', 'Container blow molding', 'Film extrusion'],
    endMarkets: ['Non-food bottles', 'Pipes', 'Household goods', 'Plastic lumber'],
    notes: 'High demand commodity plastic. Easy to recycle with good quality retention.',
  },

  {
    id: '3.3.2-ldpe-film',
    class: 3,
    subclass: '3.3',
    sku: 'POLY-LDPE-FILM',
    tradeName: 'LDPE Film Scrap',
    alternativeNames: ['Stretch film scrap', 'PE-LD film'],
    ewcCode: '15 01 02',
    ewcDescription: 'plastic packaging',
    wasteTier: 'T2',
    wasteTierDescription: 'Post-consumer/post-industrial packaging',
    specifications: {
      composition: [
        { element: 'Low-density polyethylene', range: { min: 94, max: 100 }, unit: '%' },
      ],
      physicalForm: 'Film, baled or loose',
      particleSize: { min: 50, max: 500, unit: 'mm' },
      bulkDensity: { min: 180, max: 280, unit: 'kg/mÂ³' },
      moisture: { max: 1.0, unit: '%' },
    },
    pricing: {
      basePrice: 320,
      unit: 't',
      range: { min: 250, max: 420 },
      marketIndex: 'ICIS',
      updateFrequency: 'weekly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Clean industrial stretch film, single source, colorless', priceMultiplier: 1.20, contaminationMax: 0.5, certificationRequired: false },
      { tier: 'Q2', requirements: 'Clean film, minimal contamination', priceMultiplier: 1.0, contaminationMax: 2.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Mixed film sources, some dirt acceptable', priceMultiplier: 0.75, contaminationMax: 5.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'Contaminated film, requires extensive washing', priceMultiplier: 0.50, contaminationMax: 12.0, certificationRequired: false },
    ],
    processing: {
      recyclingRoutes: ['Film recycling', 'Pelletizing', 'Downcycling to plastic lumber'],
      specialRequirements: 'Baling required for transport. Washing needed for most sources.',
      difficulty: 'medium',
      energyRequired: 2.3,
      equipmentNeeded: ['Baler', 'Wash line with friction washer', 'Agglomerator', 'Extruder'],
    },
    marketData: {
      demand: 'high',
      supply: 'very-high',
      volatility: 'medium',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 280,
      carbonAvoided: 1610,
      recyclabilityScore: 80,
      maxRecycleLoops: 4,
    },
    typicalSources: ['Pallet wrap', 'Stretch film from warehouses', 'Agricultural film', 'Grocery bags'],
    endMarkets: ['Trash bags', 'New stretch film', 'Plastic lumber', 'Film products'],
    notes: 'Large volume stream. Quality varies significantly. Requires robust washing infrastructure.',
  },

  {
    id: '3.3.3-hdpe-bottles',
    class: 3,
    subclass: '3.3',
    sku: 'POLY-HDPE-BOTT',
    tradeName: 'HDPE Bottle Grade',
    alternativeNames: ['HDPE milk bottles', 'Detergent bottles'],
    ewcCode: '15 01 02',
    ewcDescription: 'plastic packaging',
    wasteTier: 'T2',
    wasteTierDescription: 'Post-consumer packaging',
    specifications: {
      composition: [
        { element: 'High-density polyethylene', range: { min: 97, max: 100 }, unit: '%' },
      ],
      physicalForm: 'Baled bottles, flake',
      particleSize: { min: 10, max: 30, unit: 'mm' },
      bulkDensity: { min: 400, max: 550, unit: 'kg/mÂ³' },
      moisture: { max: 0.5, unit: '%' },
    },
    pricing: {
      basePrice: 540,
      unit: 't',
      range: { min: 480, max: 620 },
      marketIndex: 'ICIS',
      updateFrequency: 'weekly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Natural/white bottles, clean, caps removed', priceMultiplier: 1.15, contaminationMax: 0.5, certificationRequired: true },
      { tier: 'Q2', requirements: 'Mixed natural/white, clean', priceMultiplier: 1.0, contaminationMax: 1.5, certificationRequired: false },
      { tier: 'Q3', requirements: 'Mixed colors acceptable', priceMultiplier: 0.80, contaminationMax: 3.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'All colors, some contamination', priceMultiplier: 0.65, contaminationMax: 6.0, certificationRequired: false },],
      processing: {
        recyclingRoutes: ['Bottle-to-bottle', 'Blow molding', 'Injection molding'],
      specialRequirements: 'Remove caps, labels, wash thoroughly',
      difficulty: 'easy',
      energyRequired: 2.0,
      equipmentNeeded: ['NIR sorter', 'Label remover', 'Wash line', 'Extruder'],
    },
    marketData: {
      demand: 'very-high',
      supply: 'high',
      volatility: 'low',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 235,
      carbonAvoided: 1655,
      recyclabilityScore: 95,
      maxRecycleLoops: 7,
    },
    typicalSources: ['Curbside recycling', 'Deposit return systems', 'Commercial waste'],
    endMarkets: ['New bottles (non-food)', 'Plastic lumber', 'Drainage pipes'],
    notes: 'High-demand stream from household recycling. Natural color premium.',
  },

  {
    id: '3.3.4-lldpe-film',
    class: 3,
    subclass: '3.3',
    sku: 'POLY-LLDPE-FILM',
    tradeName: 'LLDPE Film Scrap',
    alternativeNames: ['Linear low-density PE', 'Agricultural film'],
    ewcCode: '15 01 02',
    ewcDescription: 'plastic packaging',
    wasteTier: 'T2',
    wasteTierDescription: 'Post-consumer/industrial film',
    specifications: {
      composition: [
        { element: 'Linear low-density polyethylene', range: { min: 95, max: 100 }, unit: '%' },
      ],
      physicalForm: 'Film, baled',
      particleSize: { min: 50, max: 500, unit: 'mm' },
      bulkDensity: { min: 200, max: 300, unit: 'kg/mÂ³' },
      moisture: { max: 1.0, unit: '%' },
    },
    pricing: {
      basePrice: 340,
      unit: 't',
      range: { min: 270, max: 430 },
      marketIndex: 'ICIS',
      updateFrequency: 'weekly',
    },
    qualityTiers: [
      { tier: 'Q2', requirements: 'Clean agricultural or industrial film', priceMultiplier: 1.15, contaminationMax: 2.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Standard clean film', priceMultiplier: 1.0, contaminationMax: 5.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'Dirty film, requires washing', priceMultiplier: 0.65, contaminationMax: 15.0, certificationRequired: false },
    ],
    processing: {
      recyclingRoutes: ['Film recycling', 'Pelletizing', 'Film production'],
      specialRequirements: 'Baling required, wash if contaminated',
      difficulty: 'medium',
      energyRequired: 2.4,
      equipmentNeeded: ['Baler', 'Wash line', 'Agglomerator', 'Extruder'],
    },
    marketData: {
      demand: 'high',
      supply: 'high',
      volatility: 'medium',
      seasonality: true,
    },
    environmental: {
      carbonFootprint: 290,
      carbonAvoided: 1600,
      recyclabilityScore: 82,
      maxRecycleLoops: 5,
    },
    typicalSources: ['Agricultural greenhouse film', 'Silage wrap', 'Pallet wrap'],
    endMarkets: ['New agricultural film', 'Trash bags', 'Non-food packaging'],
    notes: 'Seasonal supply from agriculture. Better mechanical properties than LDPE.',
  },

  // 3.4 POLYAMIDES (PA6, PA66, NYLON) - 3 SKUs
  {
    id: '3.4.1-pa66-natural',
    class: 3,
    subclass: '3.4',
    sku: 'POLY-PA66-NAT',
    tradeName: 'PA66 Natural Post-Industrial',
    alternativeNames: ['Nylon 66', 'Polyamide 66 regrind'],
    ewcCode: '12 01 05',
    ewcDescription: 'plastics shavings and turnings',
    wasteTier: 'T1',
    wasteTierDescription: 'By-product from injection molding',
    specifications: {
      composition: [
        { element: 'Polyamide 66', range: { min: 99, max: 100 }, unit: '%' },
      ],
      physicalForm: 'Regrind, sprues, turnings',
      particleSize: { min: 3, max: 12, unit: 'mm' },
      bulkDensity: { min: 600, max: 700, unit: 'kg/mÂ³' },
      moisture: { max: 0.3, unit: '%' },
    },
    pricing: {
      basePrice: 1850,
      unit: 't',
      range: { min: 1650, max: 2100 },
      marketIndex: 'ICIS',
      updateFrequency: 'weekly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Natural unfilled PA66, single grade (e.g., Zytel 101), virgin-like', priceMultiplier: 1.25, contaminationMax: 0.1, certificationRequired: true },
      { tier: 'Q2', requirements: 'Natural PA66, <15% glass fiber acceptable if declared', priceMultiplier: 1.0, contaminationMax: 0.5, certificationRequired: false },
      { tier: 'Q3', requirements: 'Mixture of unfilled and filled PA66, single color', priceMultiplier: 0.75, contaminationMax: 2.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'Mixed colors, glass-filled, may include some PA6', priceMultiplier: 0.55, contaminationMax: 5.0, certificationRequired: false },
    ],
    processing: {
      recyclingRoutes: ['Mechanical recycling', 'Compounding with virgin resin', 'Downgrade to lower-spec applications'],
      specialRequirements: 'Drying critical (80Â°C, 4-6 hrs). Cannot mix filled/unfilled without disclosure.',
      difficulty: 'hard',
      energyRequired: 3.8,
      equipmentNeeded: ['Granulator', 'Desiccant dryer', 'Twin-screw extruder', 'Underwater pelletizer'],
    },
    marketData: {
      demand: 'high',
      supply: 'low',
      volatility: 'high',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 580,
      carbonAvoided: 6420,
      recyclabilityScore: 75,
      maxRecycleLoops: 3,
    },
    typicalSources: ['Automotive connector molding', 'Industrial component manufacturing', 'Engineering plastics fabrication'],
    endMarkets: ['Automotive under-hood components', 'Industrial fittings', 'Electrical connectors'],
    notes: 'High-value engineering plastic. Moisture sensitive - must be dried before processing. Viscosity drops with each recycle.',
  },

  {
    id: '3.4.2-pa6-carpet-fiber',
    class: 3,
    subclass: '3.4',
    sku: 'POLY-PA6-CARPET',
    tradeName: 'PA6 Carpet Recycling',
    alternativeNames: ['Nylon 6 post-consumer', 'Carpet fiber reclaim'],
    ewcCode: '17 03 80',
    ewcDescription: 'insulation materials other than those mentioned in 17 03 01 and 17 03 02',
    wasteTier: 'T3',
    wasteTierDescription: 'Post-consumer waste requiring cleaning',
    specifications: {
      composition: [
        { element: 'Polyamide 6', range: { min: 85, max: 95 }, unit: '%' },
        { element: 'Calcium carbonate filler', range: { min: 2, max: 8 }, unit: '%' },
        { element: 'Other contaminants', range: { min: 2, max: 10 }, unit: '%' },
      ],
      physicalForm: 'Fiber, fluff, pelletized',
      particleSize: { min: 1, max: 50, unit: 'mm' },
      bulkDensity: { min: 250, max: 400, unit: 'kg/mÂ³' },
      moisture: { max: 2.0, unit: '%' },
    },
    pricing: {
      basePrice: 720,
      unit: 't',
      range: { min: 550, max: 900 },
      marketIndex: 'ICIS',
      updateFrequency: 'weekly',
    },
    qualityTiers: [
      { tier: 'Q2', requirements: 'Clean fiber separation, minimal backing contamination', priceMultiplier: 1.10, contaminationMax: 5.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Standard carpet fiber recovery', priceMultiplier: 1.0, contaminationMax: 10.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'Mixed fiber sources, higher contamination', priceMultiplier: 0.70, contaminationMax: 20.0, certificationRequired: false },
    ],
    processing: {
      recyclingRoutes: ['Depolymerization to caprolactam', 'Mechanical recycling for low-spec applications', 'Fiber-to-fiber recycling'],
      specialRequirements: 'Remove polypropylene backing, clean latex/adhesives. Consider chemical recycling for best economics.',
      difficulty: 'very-hard',
      energyRequired: 5.2,
      equipmentNeeded: ['Separation equipment', 'Wash line', 'Depolymerization reactor (chemical route)', 'Extrusion line (mechanical route)'],
    },
    marketData: {
      demand: 'medium',
      supply: 'high',
      volatility: 'medium',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 850,
      carbonAvoided: 6150,
      recyclabilityScore: 65,
      maxRecycleLoops: 99,
    },
    typicalSources: ['Carpet tile recycling programs', 'Commercial flooring removal', 'Post-consumer carpet collection'],
    endMarkets: ['Compounding for automotive parts', 'Low-spec nylon applications', 'Caprolactam monomer for virgin PA6'],
    notes: 'Chemical recycling preferred - can achieve infinite loops. Mechanical route degrades quality. Interface/Aquafil programs.',
  },

  // 3.5 POLYCARBONATE (PC) - 2 SKUs
  {
    id: '3.5.1-pc-clear',
    class: 3,
    subclass: '3.5',
    sku: 'POLY-PC-CLR',
    tradeName: 'PC Clear Regrind',
    alternativeNames: ['Polycarbonate regrind', 'PC scrap'],
    ewcCode: '12 01 05',
    ewcDescription: 'plastics shavings and turnings',
    wasteTier: 'T1',
    wasteTierDescription: 'Post-industrial by-product',
    specifications: {
      composition: [
        { element: 'Polycarbonate', range: { min: 99, max: 100 }, unit: '%' },
      ],
      physicalForm: 'Regrind, lumps',
      particleSize: { min: 5, max: 20, unit: 'mm' },
      bulkDensity: { min: 600, max: 700, unit: 'kg/mÂ³' },
      moisture: { max: 0.2, unit: '%' },
    },
    pricing: {
      basePrice: 1150,
      unit: 't',
      range: { min: 950, max: 1350 },
      marketIndex: 'ICIS',
      updateFrequency: 'weekly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Clear virgin-like PC, single grade', priceMultiplier: 1.20, contaminationMax: 0.2, certificationRequired: true },
      { tier: 'Q2', requirements: 'Clear PC, minimal yellowing', priceMultiplier: 1.0, contaminationMax: 0.5, certificationRequired: false },
      { tier: 'Q3', requirements: 'Light color, some yellowing', priceMultiplier: 0.75, contaminationMax: 2.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'Mixed colors, yellowed', priceMultiplier: 0.55, contaminationMax: 5.0, certificationRequired: false },],
      processing: {
        recyclingRoutes: ['Mechanical recycling', 'Compounding', 'Sheet extrusion'],
      specialRequirements: 'Drying critical (120Â°C, 4hrs). Avoid thermal degradation.',
      difficulty: 'medium',
      energyRequired: 3.2,
      equipmentNeeded: ['Granulator', 'Desiccant dryer', 'Extruder'],
    },
    marketData: {
      demand: 'high',
      supply: 'medium',
      volatility: 'medium',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 450,
      carbonAvoided: 5550,
      recyclabilityScore: 80,
      maxRecycleLoops: 4,
    },
    typicalSources: ['CD/DVD manufacturing', 'Automotive glazing', 'Electronics housings'],
    endMarkets: ['Automotive parts', 'Electronics', 'Safety equipment'],
    notes: 'Engineering plastic with excellent impact resistance. Yellowing reduces value.',
  },

  // 3.7 PET (Polyethylene Terephthalate) - 4 SKUs
  {
    id: '3.7LY-PA66-NAT',
    tradeName: 'PA66 Natural Post-Industrial',
    alternativeNames: ['Nylon 66', 'Polyamide 66 regrind'],
    ewcCode: '12 01 05',
    ewcDescription: 'plastics shavings and turnings',
    wasteTier: 'T1',
    wasteTierDescription: 'By-product from injection molding',
    specifications: {
      composition: [
        { element: 'Polyamide 66', range: { min: 99, max: 100 }, unit: '%' },
      ],
      physicalForm: 'Regrind, sprues, turnings',
      particleSize: { min: 3, max: 12, unit: 'mm' },
      bulkDensity: { min: 600, max: 700, unit: 'kg/mÂ³' },
      moisture: { max: 0.3, unit: '%' },
    },
    pricing: {
      basePrice: 1850,
      unit: 't',
      range: { min: 1650, max: 2100 },
      marketIndex: 'ICIS',
      updateFrequency: 'weekly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Natural unfilled PA66, single grade (e.g., Zytel 101), virgin-like', priceMultiplier: 1.25, contaminationMax: 0.1, certificationRequired: true },
      { tier: 'Q2', requirements: 'Natural PA66, <15% glass fiber acceptable if declared', priceMultiplier: 1.0, contaminationMax: 0.5, certificationRequired: false },
      { tier: 'Q3', requirements: 'Mixture of unfilled and filled PA66, single color', priceMultiplier: 0.75, contaminationMax: 2.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'Mixed colors, glass-filled, may include some PA6', priceMultiplier: 0.55, contaminationMax: 5.0, certificationRequired: false },],
      processing: {
        recyclingRoutes: ['Mechanical recycling', 'Compounding with virgin resin', "Downgrade to lower-spec applications"],
      specialRequirements: 'Drying critical (80Â°C, 4-6 hrs). Cannot mix filled/unfilled without disclosure.',
      difficulty: 'hard',
      energyRequired: 3.8,
      equipmentNeeded: ['Granulator', 'Desiccant dryer', 'Twin-screw extruder', 'Underwater pelletizer'],
    },
    marketData: {
      demand: 'high',
      supply: 'low',
      volatility: 'high',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 580,
      carbonAvoided: 6420,
      recyclabilityScore: 75,
      maxRecycleLoops: 3,
    },
    typicalSources: ['Automotive connector molding', 'Industrial component manufacturing', 'Engineering plastics fabrication'],
    endMarkets: ['Automotive under-hood components', 'Industrial fittings', 'Electrical connectors'],
    notes: 'High-value engineering plastic. Moisture sensitive - must be dried before processing. Viscosity drops with each recycle.',
  },

  {
    id: '3.6.2-pet-colored',
    class: 3,
    subclass: '3.6',
    sku: 'POLY-PET-COL',
    tradeName: 'PET Colored/Mixed',
    alternativeNames: ['Mixed color PET', 'Non-clear PET'],
    ewcCode: '15 01 02',
    ewcDescription: 'plastic packaging',
    wasteTier: 'T2',
    wasteTierDescription: 'Post-consumer packaging',
    specifications: {
      composition: [
        { element: 'Polyethylene terephthalate', range: { min: 96, max: 100 }, unit: '%' },
      ],
      physicalForm: 'Baled bottles, flake',
      particleSize: { min: 8, max: 15, unit: 'mm' },
      bulkDensity: { min: 450, max: 550, unit: 'kg/mÂ³' },
      moisture: { max: 0.8, unit: '%' },
    },
    pricing: {
      basePrice: 380,
      unit: 't',
      range: { min: 300, max: 480 },
      marketIndex: 'ICIS',
      updateFrequency: 'weekly',
    },
    qualityTiers: [
      { tier: 'Q2', requirements: 'Single color (green/blue), clean', priceMultiplier: 1.15, contaminationMax: 2.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Mixed colors, clean', priceMultiplier: 1.0, contaminationMax: 5.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'All colors, some contamination', priceMultiplier: 0.70, contaminationMax: 10.0, certificationRequired: false },
    ],
    processing: {
      recyclingRoutes: ['Fiber production', 'Strapping', 'Non-food applications'],
      specialRequirements: 'Cannot be used for food-contact. Fiber applications preferred.',
      difficulty: 'easy',
      energyRequired: 2.5,
      equipmentNeeded: ['Wash line', 'Flaking mill', 'Extrusion line'],
    },
    marketData: {
      demand: 'high',
      supply: 'high',
      volatility: 'medium',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 340,
      carbonAvoided: 2460,
      recyclabilityScore: 85,
      maxRecycleLoops: 6,
    },
    typicalSources: ['Colored beverage bottles', 'Household product bottles'],
    endMarkets: ['Polyester fiber (clothing/carpet)', 'Strapping', 'Non-food packaging'],
    notes: 'Lower value than clear but still good recycling pathway to fiber.',
  },

  {
    id: '3.6.3-pet-food-grade',
    class: 3,
    subclass: '3.6',
    sku: 'POLY-PET-FG',
    tradeName: 'PET Food-Grade Flake',
    alternativeNames: ['FDA/EFSA approved RPET', 'Food-contact PET'],
    ewcCode: '15 01 02',
    ewcDescription: 'plastic packaging',
    wasteTier: 'T2',
    wasteTierDescription: 'End-of-waste certified material',
    specifications: {
      composition: [
        { element: 'Polyethylene terephthalate', range: { min: 99, max: 100 }, unit: '%' },
      ],
      physicalForm: 'Flake after SSP treatment',
      particleSize: { min: 8, max: 12, unit: 'mm' },
      bulkDensity: { min: 500, max: 600, unit: 'kg/mÂ³' },
      moisture: { max: 0.2, unit: '%' },
    },
    pricing: {
      basePrice: 950,
      unit: 't',
      range: { min: 850, max: 1100 },
      marketIndex: 'ICIS',
      updateFrequency: 'weekly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'FDA/EFSA certified, IV >0.75, <10ppm foreign polymer', priceMultiplier: 1.10, contaminationMax: 0.1, certificationRequired: true },
      { tier: 'Q2', requirements: 'Food-grade certified, high IV', priceMultiplier: 1.0, contaminationMax: 0.3, certificationRequired: true },
    ],
    processing: {
      recyclingRoutes: ['Bottle-to-bottle recycling', 'Food packaging'],
      specialRequirements: 'SSP (solid-state polymerization) required. FDA/EFSA certification mandatory.',
      difficulty: 'hard',
      energyRequired: 3.5,
      equipmentNeeded: ['Super-clean wash', 'Extrusion', 'SSP reactor', 'IV testing'],
    },
    marketData: {
      demand: 'very-high',
      supply: 'low',
      volatility: 'high',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 380,
      carbonAvoided: 2420,
      recyclabilityScore: 95,
      maxRecycleLoops: 10,
    },
    typicalSources: ['Certified bottle collection', 'Deposit return schemes'],
    endMarkets: ['Beverage bottles', 'Food trays', 'Food packaging'],
    notes: 'Premium grade. Requires certification and advanced processing. High demand from brands.',
  },

  // 3.7 ENGINEERING PLASTICS (PEEK, PTFE, PEI) - 2 SKUs
  {
    id: '3.7.1-peek-natural',
    class: 3,
    subclass: '3.7',
    sku: 'POLY-POM-NAT',
    tradeName: 'POM Natural Post-Industrial',
    alternativeNames: ['Acetal copolymer regrind', 'Delrin scrap', 'Polyacetal'],
    ewcCode: '12 01 05',
    ewcDescription: 'plastics shavings and turnings',
    wasteTier: 'T1',
    wasteTierDescription: 'By-product from injection molding/machining',
    specifications: {
      composition: [
        { element: 'Polyoxymethylene copolymer', range: { min: 99, max: 100 }, unit: '%' },
      ],
      physicalForm: 'Regrind, turnings, sprues',
      particleSize: { min: 2, max: 10, unit: 'mm' },
      bulkDensity: { min: 650, max: 750, unit: 'kg/mÂ³' },
      moisture: { max: 0.2, unit: '%' },
    },
    pricing: {
      basePrice: 1420,
      unit: 't',
      range: { min: 1250, max: 1650 },
      marketIndex: 'ICIS',
      updateFrequency: 'weekly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Natural/white color, single grade (e.g., Delrin 500), no contamination', priceMultiplier: 1.18, contaminationMax: 0.2, certificationRequired: true },
      { tier: 'Q2', requirements: 'Single color, clean machining turnings', priceMultiplier: 1.0, contaminationMax: 0.5, certificationRequired: false },
      { tier: 'Q3', requirements: 'Mixed colors, POM only, no metal contamination', priceMultiplier: 0.80, contaminationMax: 2.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'Mixed POM, some additives/fillers acceptable', priceMultiplier: 0.60, contaminationMax: 5.0, certificationRequired: false },],
      processing: {
        recyclingRoutes: ['Mechanical recycling', 'Compounding with virgin POM', 'Downgrade to lower-spec applications'],
      specialRequirements: 'Avoid thermal degradation - process at <200Â°C. Stabilizers required.',
      difficulty: 'hard',
      energyRequired: 3.2,
      equipmentNeeded: ['Granulator', 'Drying equipment', 'Extruder with stabilization additives'],
    },
    marketData: {
      demand: 'medium',
      supply: 'low',
      volatility: 'medium',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 420,
      carbonAvoided: 2780,
      recyclabilityScore: 70,
      maxRecycleLoops: 3,
    },
    typicalSources: ['Precision machining', 'Gears and bearings manufacturing', 'Automotive component molding'],
    endMarkets: ['Automotive gears', 'Zippers', 'Precision parts', 'Conveyor components'],
    notes: 'Engineering plastic with excellent mechanical properties. Thermal sensitivity limits recycle loops.',
  },

  {
    id: '3.7.2-ptfe-turnings',
    class: 3,
    subclass: '3.7',
    sku: 'POLY-PTFE-TURN',
    tradeName: 'PTFE Turnings & Offcuts',
    alternativeNames: ['Teflon scrap', 'PTFE machining waste', 'Fluoropolymer reclaim'],
    ewcCode: '12 01 05',
    ewcDescription: 'plastics shavings and turnings',
    wasteTier: 'T1',
    wasteTierDescription: 'By-product from machining operations',
    specifications: {
      composition: [
        { element: 'Polytetrafluoroethylene', range: { min: 98, max: 100 }, unit: '%' },
      ],
      physicalForm: 'Turnings, chips, sheet offcuts',
      particleSize: { min: 0.5, max: 50, unit: 'mm' },
      bulkDensity: { min: 400, max: 550, unit: 'kg/mÂ³' },
      moisture: { max: 0.2, unit: '%' },
    },
    pricing: {
      basePrice: 4200,
      unit: 't',
      range: { min: 3500, max: 5000 },
      marketIndex: 'ICIS',
      updateFrequency: 'monthly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Virgin PTFE turnings, white/off-white, clean, no filler', priceMultiplier: 1.25, contaminationMax: 0.5, certificationRequired: true },
      { tier: 'Q2', requirements: 'Clean turnings, unfilled PTFE only', priceMultiplier: 1.0, contaminationMax: 2.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Filled PTFE acceptable (glass, bronze, carbon)', priceMultiplier: 0.65, contaminationMax: 5.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'Mixed PTFE sources, some contamination', priceMultiplier: 0.45, contaminationMax: 10.0, certificationRequired: false },
    ],
    processing: {
      recyclingRoutes: ['Grinding to reprocessable powder', 'Micronization for coatings', 'Additive in compounds'],
      specialRequirements: 'Cannot be melt-processed (no melting point). Cryogenic grinding required for fine powder.',
      difficulty: 'very-hard',
      energyRequired: 8.5,
      equipmentNeeded: ['Cryogenic grinder', 'Jet mill for micronization', 'Classification equipment'],
    },
    marketData: {
      demand: 'medium',
      supply: 'low',
      volatility: 'low',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 2800,
      carbonAvoided: 11200,
      recyclabilityScore: 60,
      maxRecycleLoops: 99,
    },
    typicalSources: ['Gasket and seal manufacturing', 'Chemical equipment machining', 'Coating production'],
    endMarkets: ['Low-friction additives', 'Coating powder', 'Ram extrusion products', 'Compression molding'],
    notes: 'High-value fluoropolymer. Cannot be melted/extruded like thermoplastics. Grinding to powder is primary recycling route.',
  },

  // 3.8 POLYSTYRENE (PS, EPS, HIPS) - 2 SKUs
  {
    id: '3.8.1-hips-post-industrial',
    class: 3,
    subclass: '3.8',
    wasteTier: 'T2',
    wasteTierDescription: 'Post-consumer packaging with end-of-waste potential',
    specifications: {
      composition: [
        { element: 'Polyethylene terephthalate', range: { min: 98, max: 100 }, unit: '%' },
      ],
      physicalForm: 'Baled bottles, flake after wash',
      particleSize: { min: 8, max: 15, unit: 'mm' },
      bulkDensity: { min: 450, max: 550, unit: 'kg/mÂ³' },
      moisture: { max: 0.5, unit: '%' },
    },
    pricing: {
      basePrice: 680,
      unit: 't',
      range: { min: 550, max: 850 },
      marketIndex: 'ICIS',
      updateFrequency: 'weekly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Clear bottles only, food-grade wash, <50ppm foreign polymer, FDA/EFSA cert', priceMultiplier: 1.30, contaminationMax: 0.5, certificationRequired: true },
      { tier: 'Q2', requirements: 'Clear bottles, standard wash, <200ppm contamination', priceMultiplier: 1.0, contaminationMax: 2.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Mixed clear and light blue, clean', priceMultiplier: 0.75, contaminationMax: 5.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'Mixed colors, some contamination acceptable', priceMultiplier: 0.50, contaminationMax: 10.0, certificationRequired: false },],
      processing: {
        recyclingRoutes: ['Bottle-to-bottle recycling', 'Fiber production', 'Sheet/thermoforming', 'Strapping'],
      specialRequirements: 'Remove caps/labels, wash thoroughly. Food-contact requires SSP (solid-state polymerization).',
      difficulty: 'medium',
      energyRequired: 2.6,
      equipmentNeeded: ['Sorting system (NIR)', 'Label remover', 'Hot wash (caustic)', 'Flaking mill', 'Extrusion line', 'SSP reactor (food grade)'],
    },
    marketData: {
      demand: 'very-high',
      supply: 'high',
      volatility: 'medium',
      seasonality: true,
    },
    environmental: {
      carbonFootprint: 320,
      carbonAvoided: 2480,
      recyclabilityScore: 90,
      maxRecycleLoops: 7,
    },
    typicalSources: ['Beverage bottles (water, soda)', 'Deposit return schemes', 'Curbside recycling', 'Commercial collections'],
    endMarkets: ['New beverage bottles', 'Textile fiber (polyester)', 'Food packaging', 'Strapping'],
    notes: 'High-demand recycled plastic. Clear commands premium. Food-grade certification crucial for highest value.',
  },

  // 3.7 ENGINEERING PLASTICS (PEEK, PTFE, PEI) - 9 SKUs
  {
    id: '3.7.1-peek-natural',
    class: 3,
    subclass: '3.7',
    sku: 'POLY-PEEK-NAT',
    tradeName: 'PEEK Natural Post-Industrial',
    alternativeNames: ['Polyetheretherketone scrap', 'PEEK machining waste'],
    ewcCode: '12 01 05',
    ewcDescription: 'plastics shavings and turnings',
    wasteTier: 'T1',
    wasteTierDescription: 'High-value by-product from machining',
    specifications: {
      composition: [
        { element: 'Polyetheretherketone', range: { min: 99, max: 100 }, unit: '%' },
      ],
      physicalForm: 'Turnings, chips, sprues',
      particleSize: { min: 1, max: 20, unit: 'mm' },
      bulkDensity: { min: 600, max: 700, unit: 'kg/mÂ³' },
      moisture: { max: 0.1, unit: '%' },
    },
    pricing: {
      basePrice: 28000,
      unit: 't',
      range: { min: 24000, max: 32000 },
      marketIndex: 'ICIS',
      updateFrequency: 'monthly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Natural/tan unfilled PEEK, single grade, clean machining waste', priceMultiplier: 1.15, contaminationMax: 0.1, certificationRequired: true },
      { tier: 'Q2', requirements: 'Unfilled PEEK, minimal contamination', priceMultiplier: 1.0, contaminationMax: 0.5, certificationRequired: false },
      { tier: 'Q3', requirements: 'Carbon-filled or glass-filled PEEK acceptable if declared', priceMultiplier: 0.70, contaminationMax: 1.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'Mixed PEEK grades, some contamination', priceMultiplier: 0.50, contaminationMax: 3.0, certificationRequired: false },],
      processing: {
        recyclingRoutes: ['Mechanical recycling', 'Compounding with virgin PEEK', 'Powder for additive manufacturing'],
      specialRequirements: 'Cannot mix filled/unfilled. High processing temperature (380-400Â°C) requires special equipment.',
      difficulty: 'very-hard',
      energyRequired: 5.8,
      equipmentNeeded: ['Granulator', 'High-temp drying (150Â°C)', 'High-temp extruder', 'Cryogenic grinding (for powder)'],
    },
    marketData: {
      demand: 'medium',
      supply: 'very-low',
      volatility: 'low',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 1200,
      carbonAvoided: 8800,
      recyclabilityScore: 65,
      maxRecycleLoops: 2,
    },
    typicalSources: ['Aerospace machining', 'Medical implant manufacturing', 'Oil & gas component fabrication'],
    endMarkets: ['Industrial bushings', 'Seals and gaskets', 'Aerospace non-structural parts', '3D printing filament'],
    notes: 'Ultra-premium engineering plastic. Very high virgin cost ($30-45/kg) makes recycling economically attractive despite processing challenges.',
  },

  {
    id: '3.7.2-ptfe-turnings',
    class: 3,
    subclass: '3.7',
    sku: 'POLY-PTFE-TURN',
    tradeName: 'PTFE Turnings & Offcuts',
    alternativeNames: ['Teflon scrap', 'PTFE machining waste', 'Fluoropolymer reclaim'],
    ewcCode: '12 01 05',
    ewcDescription: 'plastics shavings and turnings',
    wasteTier: 'T1',
    wasteTierDescription: 'By-product from machining operations',
    specifications: {
      composition: [
        { element: 'Polytetrafluoroethylene', range: { min: 98, max: 100 }, unit: '%' },
      ],
      physicalForm: 'Turnings, chips, sheet offcuts',
      particleSize: { min: 0.5, max: 50, unit: 'mm' },
      bulkDensity: { min: 400, max: 550, unit: 'kg/mÂ³' },
      moisture: { max: 0.2, unit: '%' },
    },
    pricing: {
      basePrice: 4200,
      unit: 't',
      range: { min: 3500, max: 5000 },
      marketIndex: 'ICIS',
      updateFrequency: 'monthly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Virgin PTFE turnings, white/off-white, clean, no filler', priceMultiplier: 1.25, contaminationMax: 0.5, certificationRequired: true },
      { tier: 'Q2', requirements: 'Clean turnings, unfilled PTFE only', priceMultiplier: 1.0, contaminationMax: 2.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Filled PTFE acceptable (glass, bronze, carbon)', priceMultiplier: 0.65, contaminationMax: 5.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'Mixed PTFE sources, some contamination', priceMultiplier: 0.45, contaminationMax: 10.0, certificationRequired: false },],
      processing: {
        recyclingRoutes: ['Grinding to reprocessable powder', 'Micronization for coatings', 'Additive in compounds'],
      specialRequirements: 'Cannot be melt-processed (no melting point). Cryogenic grinding required for fine powder.',
      difficulty: 'very-hard',
      energyRequired: 8.5,
      equipmentNeeded: ['Cryogenic grinder', 'Jet mill for micronization', 'Classification equipment'],
    },
    marketData: {
      demand: 'medium',
      supply: 'low',
      volatility: 'low',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 2800,
      carbonAvoided: 11200,
      recyclabilityScore: 60,
      maxRecycleLoops: 99,
    },
    typicalSources: ['Gasket and seal manufacturing', 'Chemical equipment machining', 'Coating production'],
    endMarkets: ['Low-friction additives', 'Coating powder', 'Ram extrusion products', 'Compression molding'],
    notes: 'High-value fluoropolymer. Cannot be melted/extruded like thermoplastics. Grinding to powder is primary recycling route.',
  },

  // 3.8 POLYSTYRENE (PS, EPS, HIPS) - 2 SKUs
  {
    id: '3.8.1-hips-post-industrial',
    class: 3,
    subclass: '3.8',
    sku: 'POLY-HIPS-PI',
    tradeName: 'HIPS Post-Industrial',
    alternativeNames: ['High Impact Polystyrene regrind', 'HIPS scrap'],
    ewcCode: '12 01 05',
    ewcDescription: 'plastics shavings and turnings',
    wasteTier: 'T1',
    wasteTierDescription: 'By-product from thermoforming',
    specifications: {
      composition: [
        { element: 'Polystyrene', range: { min: 90, max: 95 }, unit: '%' },
        { element: 'Polybutadiene (rubber)', range: { min: 5, max: 10 }, unit: '%' },
      ],
      physicalForm: 'Regrind, sheet trim',
      particleSize: { min: 5, max: 25, unit: 'mm' },
      bulkDensity: { min: 500, max: 600, unit: 'kg/mÂ³' },
      moisture: { max: 0.3, unit: '%' },
    },
    pricing: {
      basePrice: 420,
      unit: 't',
      range: { min: 350, max: 520 },
      marketIndex: 'ICIS',
      updateFrequency: 'weekly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Single color (white preferred), clean trim from thermoforming', priceMultiplier: 1.15, contaminationMax: 0.5, certificationRequired: false },
      { tier: 'Q2', requirements: 'Single color, HIPS only, no GPPS contamination', priceMultiplier: 1.0, contaminationMax: 2.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Mixed colors acceptable, clean', priceMultiplier: 0.80, contaminationMax: 5.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'Mixed PS types, some contamination', priceMultiplier: 0.60, contaminationMax: 10.0, certificationRequired: false },],
      processing: {
        recyclingRoutes: ['Mechanical recycling', 'Thermoforming applications', 'Injection molding'],
      specialRequirements: 'Avoid mixing with GPPS - different impact properties. No EPS foam contamination.',
      difficulty: 'easy',
      energyRequired: 2.2,
      equipmentNeeded: ['Granulator', 'Extrusion line'],
    },
    marketData: {
      demand: 'medium',
      supply: 'medium',
      volatility: 'medium',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 280,
      carbonAvoided: 2820,
      recyclabilityScore: 85,
      maxRecycleLoops: 4,
    },
    typicalSources: ['Refrigerator liner production', 'Disposable cups/containers', 'Yogurt cup manufacturing'],
    endMarkets: ['Non-food thermoformed products', 'Office supplies', 'Toys, Picture frames'],
    notes: 'Commodity plastic. Easy to recycle but lower value than engineering plastics.',
  },

  {
    id: '3.8.2-eps-clean',
    class: 3,
    subclass: '3.8',
    sku: 'POLY-EPS-CLN',
    tradeName: 'EPS Clean Post-Industrial',
    alternativeNames: ['Expanded polystyrene foam', 'Styrofoam scrap', 'EPS blocks'],
    ewcCode: '15 01 02',
    ewcDescription: 'plastic packaging',
    wasteTier: 'T2',
    wasteTierDescription: 'Packaging waste with recycling pathway',
    specifications: {
      composition: [
        { element: 'Polystyrene (expanded)', range: { min: 98, max: 100 }, unit: '%' },
      ],
      physicalForm: 'Foam blocks, packaging shapes',
      particleSize: { min: 50, max: 500, unit: 'mm' },
      bulkDensity: { min: 15, max: 30, unit: 'kg/mÂ³' },
      moisture: { max: 2.0, unit: '%' },
    },
    pricing: {
      basePrice: 180,
      unit: 't',
      range: { min: 120, max: 280 },
      marketIndex: 'ICIS',
      updateFrequency: 'weekly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Clean white EPS, no tape/labels, single source', priceMultiplier: 1.40, contaminationMax: 1.0, certificationRequired: false },
      { tier: 'Q2', requirements: 'Clean EPS, minimal tape acceptable', priceMultiplier: 1.0, contaminationMax: 3.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Mixed EPS sources, some contamination', priceMultiplier: 0.65, contaminationMax: 8.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'Dirty EPS, food contact acceptable if washable', priceMultiplier: 0.40, contaminationMax: 15.0, certificationRequired: false },],
      processing: {
        recyclingRoutes: ['Densification (compaction)', 'Solvent dissolution', 'Thermal densification', 'Pyrolysis to styrene monomer'],
      specialRequirements: 'Must densify before transport (40:1 reduction). Remove adhesives/tape.',
      difficulty: 'medium',
      energyRequired: 1.8,
      equipmentNeeded: ['Densifier/compactor', 'Wash equipment', 'Extrusion line'],
    },
    marketData: {
      demand: 'low',
      supply: 'very-high',
      volatility: 'high',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 450,
      carbonAvoided: 2550,
      recyclabilityScore: 70,
      maxRecycleLoops: 3,
    },
    typicalSources: ['Electronics packaging', 'Appliance shipping', 'Fish boxes', 'Construction insulation'],
    endMarkets: ['Picture frames', 'Crown molding', 'Insulation board', 'Styrene monomer (chemical recycling)'],
    notes: 'Low bulk density makes collection/transport expensive. Densification essential for viability.',
  },

  // 3.9 PVC (POLYVINYL CHLORIDE) - 1 SKU
  {
    id: '3.9.1-pvc-rigid',
    class: 3,
    subclass: '3.9',
    sku: 'POLY-PVC-RIG',
    tradeName: 'PVC Rigid Scrap',
    alternativeNames: ['uPVC', 'Rigid PVC regrind', 'Window profile scrap'],
    ewcCode: '17 02 03',
    ewcDescription: 'plastic',
    wasteTier: 'T2',
    wasteTierDescription: 'Post-consumer/industrial waste',
    specifications: {
      composition: [
        { element: 'Polyvinyl chloride', range: { min: 95, max: 100 }, unit: '%' },
      ],
      physicalForm: 'Regrind, window profiles, pipe offcuts',
      particleSize: { min: 5, max: 30, unit: 'mm' },
      bulkDensity: { min: 600, max: 750, unit: 'kg/mÂ³' },
      moisture: { max: 0.5, unit: '%' },
    },
    pricing: {
      basePrice: 420,
      unit: 't',
      range: { min: 350, max: 520 },
      marketIndex: 'ICIS',
      updateFrequency: 'weekly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Post-industrial, single color (white), clean profiles', priceMultiplier: 1.20, contaminationMax: 0.5, certificationRequired: false },
      { tier: 'Q2', requirements: 'Clean rigid PVC, light colors', priceMultiplier: 1.0, contaminationMax: 2.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Mixed colors, clean', priceMultiplier: 0.75, contaminationMax: 5.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'Contaminated, weathered material', priceMultiplier: 0.55, contaminationMax: 10.0, certificationRequired: false },
    ],
    processing: {
      recyclingRoutes: ['Mechanical recycling', 'Pipe/profile production', 'Compounding'],
      specialRequirements: 'Remove metal reinforcement. Avoid mixing with flexible PVC.',
      difficulty: 'medium',
      energyRequired: 2.3,
      equipmentNeeded: ['Granulator', 'Metal separator', 'Extruder with HCl scrubbing'],
    },
    marketData: {
      demand: 'medium',
      supply: 'medium',
      volatility: 'low',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 320,
      carbonAvoided: 1680,
      recyclabilityScore: 75,
      maxRecycleLoops: 5,
    },
    typicalSources: ['Window replacement', 'Pipe manufacturing', 'Construction demolition'],
    endMarkets: ['New pipes', 'Window profiles', 'Decking', 'Road barriers'],
    notes: 'Well-established recycling infrastructure in Europe. Must handle HCl emissions.',
  },

  // 3.10 CONTAMINATED / MULTI-LAYER FILMS - 2 SKUs
  {
    id: '3.10.1-multilayer-film',
    class: 3,
    subclass: '3.10',
    sku: 'POLY-ML-FILM',
    tradeName: 'Multi-Layer Film Waste',
    alternativeNames: ['Coextruded film', 'Laminated film', 'Barrier film'],
    ewcCode: '15 01 02',
    ewcDescription: 'plastic packaging',
    wasteTier: 'T3',
    wasteTierDescription: 'Composite waste requiring specialized processing',
    specifications: {
      composition: [
        { element: 'Polyethylene layers', range: { min: 40, max: 70 }, unit: '%' },
        { element: 'EVOH/PA barrier layers', range: { min: 5, max: 15 }, unit: '%' },
        { element: 'Adhesive layers', range: { min: 2, max: 5 }, unit: '%' },
        { element: 'Other polymers', range: { min: 15, max: 40 }, unit: '%' },
      ],
      physicalForm: 'Baled film, roll ends',
      particleSize: { min: 100, max: 1000, unit: 'mm' },
      bulkDensity: { min: 200, max: 300, unit: 'kg/mÂ³' },
      moisture: { max: 1.0, unit: '%' },
    },
    pricing: {
      basePrice: 85,
      unit: 't',
      range: { min: 40, max: 150 },
      marketIndex: 'ICIS',
      updateFrequency: 'weekly',
    },
    qualityTiers: [
      { tier: 'Q2', requirements: 'Clean post-industrial trim, known layer structure', priceMultiplier: 1.50, contaminationMax: 2.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Mixed multi-layer sources, relatively clean', priceMultiplier: 1.0, contaminationMax: 8.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'Contaminated multi-layer film, food residue acceptable', priceMultiplier: 0.60, contaminationMax: 20.0, certificationRequired: false },
    ],
    processing: {
      recyclingRoutes: ['Compatible layer recycling (compat)', 'Energy recovery', 'Chemical recycling (pyrolysis)', 'Gasification'],
      specialRequirements: 'Cannot separate layers mechanically. Pyrolysis or energy recovery preferred. Compat technology emerging.',
      difficulty: 'very-hard',
      energyRequired: 4.5,
      equipmentNeeded: ['Pyrolysis reactor', 'Energy-from-waste facility', 'Compat extrusion technology'],
    },
    marketData: {
      demand: 'very-low',
      supply: 'very-high',
      volatility: 'high',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 650,
      carbonAvoided: 450,
      recyclabilityScore: 25,
      maxRecycleLoops: 1,
    },
    typicalSources: ['Food packaging production', 'Snack food bags', 'Modified atmosphere packaging', 'Pharmaceutical blister packs'],
    endMarkets: ['Pyrolysis oil', 'Refuse-derived fuel', 'Plastic lumber (downcycled)', 'Chemical feedstock'],
    notes: 'Difficult-to-recycle stream. Low value. Chemical recycling or energy recovery main outlets. Avoid designing these.',
  },

  {
    id: '3.9.2-silicone-contaminated',
    class: 3,
    subclass: '3.9',
    sku: 'POLY-SI-CONT',
    tradeName: 'Silicone-Contaminated Plastics',
    alternativeNames: ['Silicone waste', 'LSR-contaminated scrap'],
    ewcCode: '12 01 05',
    ewcDescription: 'plastics shavings and turnings',
    wasteTier: 'T3',
    wasteTierDescription: 'Contaminated waste with limited recycling options',
    specifications: {
      composition: [
        { element: 'Thermoplastic (PP/ABS/PA)', range: { min: 70, max: 95 }, unit: '%' },
        { element: 'Silicone rubber (LSR)', range: { min: 5, max: 30 }, unit: '%' },
      ],
      physicalForm: 'Regrind, two-shot molded parts',
      particleSize: { min: 3, max: 20, unit: 'mm' },
      bulkDensity: { min: 500, max: 650, unit: 'kg/mÂ³' },
      moisture: { max: 0.5, unit: '%' },
    },
    pricing: {
      basePrice: 45,
      unit: 't',
      range: { min: 20, max: 80 },
      marketIndex: 'ICIS',
      updateFrequency: 'monthly',
    },
    qualityTiers: [
      { tier: 'Q3', requirements: 'Known base resin, consistent silicone content', priceMultiplier: 1.20, contaminationMax: 30.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'Mixed resins, variable silicone contamination', priceMultiplier: 1.0, contaminationMax: 50.0, certificationRequired: false },
    ],
    processing: {
      recyclingRoutes: ['Energy recovery (incineration)', 'Cement kiln fuel', 'Pyrolysis (experimental)'],
      specialRequirements: 'Silicone cannot be removed. Ruins conventional plastic recycling. Energy recovery or disposal.',
      difficulty: 'very-hard',
      energyRequired: 0.0,
      equipmentNeeded: ['Waste-to-energy facility', 'Cement kiln'],
    },
    marketData: {
      demand: 'very-low',
      supply: 'low',
      volatility: 'low',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 800,
      carbonAvoided: 50,
      recyclabilityScore: 10,
      maxRecycleLoops: 0,
    },
    typicalSources: ['Two-shot molding (phone cases)', 'Medical device manufacturing', 'Automotive sealing components'],
    endMarkets: ['Incineration with energy recovery', 'Cement production (fuel substitute)'],
    notes: 'Nightmare material for recycling. Silicone contaminates thermoplastic recycling streams. Design for disassembly critical.',
  },
];

export const POLYMERS_CLASS: MaterialClass = {
  classNumber: 3,
  className: 'Polymers & Plastics',
  description: 'Thermoplastics from commodity to engineering grades, post-industrial and post-consumer streams',
  skuCount: 112,
  materials: POLYMERS,
};

export default POLYMERS;
