/**
 * CLASS 4: PROCESS CHEMICALS (20 SKUs - Most Common)
 * Metalworking fluids, oils, solvents, plating baths
 * Mostly T3/T4 hazardous waste requiring specialized handling
 */

import { MaterialSKU, MaterialClass } from './types';

export const PROCESS_CHEMICALS: MaterialSKU[] = [
  // 4.1 METALWORKING FLUIDS - 6 SKUs
  {
    id: '4.1.1-cutting-fluid-water',
    class: 4,
    subclass: '4.1',
    sku: 'CHEM-CF-WATER',
    tradeName: 'Water-Soluble Cutting Fluid (Used)',
    alternativeNames: ['Coolant emulsion', 'Cutting oil emulsion', 'Metalworking fluid'],
    ewcCode: '12 01 09*',
    ewcDescription: 'machining emulsions and solutions containing halogens',
    wasteTier: 'T4',
    wasteTierDescription: 'Hazardous waste - contaminated with metal fines and oils',
    hazard: {
      unNumber: 'N/A',
      adrClass: undefined,
      packingGroup: undefined,
      hProperties: ['H4', 'H5', 'H14'],
      transportRestrictions: 'Check local regulations for transport',
    },
    specifications: {
      composition: [
        { element: 'Water', range: { min: 85, max: 95 }, unit: '%' },
        { element: 'Mineral oil', range: { min: 3, max: 10 }, unit: '%' },
        { element: 'Metal fines (Fe, Al, Cu)', range: { min: 0.5, max: 5 }, unit: '%' },
      ],
      physicalForm: 'Liquid emulsion',
      bulkDensity: { min: 1000, max: 1050, unit: 'kg/mÂ³' },
    },
    pricing: {
      basePrice: -45,
      unit: 't',
      range: { min: -80, max: -20 },
      marketIndex: 'OPIS',
      updateFrequency: 'monthly',
    },
    qualityTiers: [
      { tier: 'Q2', requirements: 'Low metal content (<2%), pH stable, no biological growth', priceMultiplier: 1.30, contaminationMax: 2.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Standard used coolant, metal fines acceptable', priceMultiplier: 1.0, contaminationMax: 5.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'Highly contaminated, biological degradation', priceMultiplier: 0.70, contaminationMax: 15.0, certificationRequired: false },
    ],
    processing: {
      recyclingRoutes: ['Ultrafiltration and reuse', 'Oil-water separation', 'Incineration', 'Biological treatment'],
      specialRequirements: 'Hazardous waste license required. ADR-compliant transport.',
      difficulty: 'hard',
      energyRequired: 1.5,
      equipmentNeeded: ['Ultrafiltration unit', 'Centrifuge', 'Oil skimmer', 'Wastewater treatment'],
    },
    marketData: {
      demand: 'medium',
      supply: 'very-high',
      volatility: 'low',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 850,
      carbonAvoided: 200,
      recyclabilityScore: 45,
      maxRecycleLoops: 2,
    },
    typicalSources: ['Machine shops', 'Automotive manufacturing', 'Metal fabrication'],
    endMarkets: ['Reconditioning for reuse', 'Wastewater treatment', 'Waste-to-energy'],
    notes: 'Negative pricing = generator pays for disposal. Better management can extend life and reduce disposal costs.',
  },

  {
    id: '4.1.2-cutting-oil-neat',
    class: 4,
    subclass: '4.1',
    sku: 'CHEM-CF-NEAT',
    tradeName: 'Neat Cutting Oil (Used)',
    alternativeNames: ['Straight cutting oil', 'Neat oil'],
    ewcCode: '12 01 07*',
    ewcDescription: 'mineral-based machining oils containing halogens',
    wasteTier: 'T4',
    wasteTierDescription: 'Hazardous waste oil',
    hazard: {
      unNumber: 'UN 1270',
      adrClass: '3',
      packingGroup: 'III',
      hProperties: ['H3', 'H5', 'H12'],
      transportRestrictions: 'Flammable liquid - ADR packaging required',
    },
    specifications: {
      composition: [
        { element: 'Mineral oil', range: { min: 90, max: 98 }, unit: '%' },
        { element: 'Metal fines', range: { min: 1, max: 8 }, unit: '%' },
      ],
      physicalForm: 'Liquid',
      bulkDensity: { min: 850, max: 920, unit: 'kg/mÂ³' },
    },
    pricing: {
      basePrice: -25,
      unit: 't',
      range: { min: -50, max: 10 },
      marketIndex: 'OPIS',
      updateFrequency: 'monthly',
    },
    qualityTiers: [
      { tier: 'Q2', requirements: 'Low metal content, can be cleaned and reused', priceMultiplier: 1.50, contaminationMax: 3.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Standard used neat oil', priceMultiplier: 1.0, contaminationMax: 8.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'Highly contaminated with metals', priceMultiplier: 0.65, contaminationMax: 20.0, certificationRequired: false },],
      processing: {
        recyclingRoutes: ['Centrifugal cleaning and reuse', 'Re-refining', 'Industrial fuel blending', 'Incineration'],
      specialRequirements: 'Hazardous waste handling. Remove metal fines via settling/centrifuge.',
      difficulty: 'medium',
      energyRequired: 0.8,
      equipmentNeeded: ['Centrifuge', 'Settling tank', 'Magnetic separator'],
    },
    marketData: {
      demand: 'low',
      supply: 'high',
      volatility: 'medium',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 650,
      carbonAvoided: 450,
      recyclabilityScore: 55,
      maxRecycleLoops: 3,
    },
    typicalSources: ['Heavy machining operations', 'Threading/tapping operations', 'Gear cutting'],
    endMarkets: ['Reconditioning service', 'Industrial fuel', 'Re-refining to base oil'],
    notes: 'Higher recovery value than water-soluble fluids. Metal fines can be recovered.',
  },

  {
    id: '4.1.3-drawing-oil',
    class: 4,
    subclass: '4.1',
    sku: 'CHEM-DRAW-OIL',
    tradeName: 'Used Drawing Oil',
    alternativeNames: ['Forming oil', 'Stamping oil'],
    ewcCode: '12 01 12*',
    ewcDescription: 'spent waxes and fats',
    wasteTier: 'T4',
    wasteTierDescription: 'Hazardous waste oil',
    hazard: {
      unNumber: 'UN 3082',
      adrClass: '9',
      packingGroup: 'III',
      hProperties: ['H5', 'H14'],
      transportRestrictions: 'Marine pollutant',
    },
    specifications: {
      composition: [
        { element: 'Mineral oil base', range: { min: 85, max: 95 }, unit: '%' },
        { element: 'Fatty acid additives', range: { min: 3, max: 10 }, unit: '%' },
        { element: 'Metal particles', range: { min: 1, max: 5 }, unit: '%' },
      ],
      physicalForm: 'Viscous liquid',
      bulkDensity: { min: 880, max: 950, unit: 'kg/mÂ³' },
    },
    pricing: {
      basePrice: -15,
      unit: 't',
      range: { min: -40, max: 20 },
      marketIndex: 'OPIS',
      updateFrequency: 'monthly',
    },
    qualityTiers: [
      { tier: 'Q2', requirements: 'Clean oil, filterable, reusable', priceMultiplier: 1.40, contaminationMax: 2.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Standard used oil', priceMultiplier: 1.0, contaminationMax: 5.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'Contaminated with coolant or sludge', priceMultiplier: 0.60, contaminationMax: 15.0, certificationRequired: false },],
      processing: {
        recyclingRoutes: ['Filtration and reuse', 'Re-refining', 'Industrial fuel'],
      specialRequirements: 'Keep separate from cutting fluids. Filter metal particles.',
      difficulty: 'easy',
      energyRequired: 0.5,
      equipmentNeeded: ['Filtration unit', 'Settling tank'],
    },
    marketData: {
      demand: 'medium',
      supply: 'medium',
      volatility: 'low',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 550,
      carbonAvoided: 600,
      recyclabilityScore: 65,
      maxRecycleLoops: 4,
    },
    typicalSources: ['Sheet metal stamping', 'Deep drawing operations', 'Wire drawing'],
    endMarkets: ['Reconditioning for reuse', 'Re-refining', 'Industrial heating'],
    notes: 'Relatively clean waste oil. Good potential for filtration and reuse.',
  },

  // 4.2 USED OILS - 5 SKUs
  {
    id: '4.2.1-motor-oil-used',
    class: 4,
    subclass: '4.2',
    sku: 'CHEM-MOTOR-OIL',
    tradeName: 'Used Motor Oil',
    alternativeNames: ['Waste engine oil', 'UMO', 'Crankcase oil'],
    ewcCode: '13 02 05*',
    ewcDescription: 'mineral-based non-chlorinated engine, gear and lubricating oils',
    wasteTier: 'T4',
    wasteTierDescription: 'Hazardous waste oil',
    hazard: {
      unNumber: 'UN 3082',
      adrClass: '9',
      packingGroup: 'III',
      hProperties: ['H5', 'H14'],
      transportRestrictions: 'Marine pollutant. Keep separate from PCB-contaminated oils.',
    },
    specifications: {
      composition: [
        { element: 'Mineral oil base', range: { min: 75, max: 90 }, unit: '%' },
        { element: 'Oxidation products', range: { min: 5, max: 15 }, unit: '%' },
        { element: 'Contaminants (soot, fuel, metals)', range: { min: 3, max: 10 }, unit: '%' },
      ],
      physicalForm: 'Dark liquid',
      bulkDensity: { min: 870, max: 920, unit: 'kg/mÂ³' },
    },
    pricing: {
      basePrice: 80,
      unit: 't',
      range: { min: 40, max: 140 },
      marketIndex: 'OPIS',
      updateFrequency: 'weekly',
    },
    qualityTiers: [
      { tier: 'Q2', requirements: 'Automotive only, no industrial contaminants, <1000ppm water', priceMultiplier: 1.25, contaminationMax: 5.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Standard used motor oil', priceMultiplier: 1.0, contaminationMax: 10.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'Mixed with other oils or high water content', priceMultiplier: 0.60, contaminationMax: 25.0, certificationRequired: false },
    ],
    processing: {
      recyclingRoutes: ['Re-refining to base oil', 'Industrial fuel', 'Road oil/asphalt'],
      specialRequirements: 'Test for PCBs. Remove water and sediment.',
      difficulty: 'medium',
      energyRequired: 1.2,
      equipmentNeeded: ['Dewatering unit', 'Re-refining plant', 'Vacuum distillation'],
    },
    marketData: {
      demand: 'high',
      supply: 'very-high',
      volatility: 'medium',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 450,
      carbonAvoided: 2100,
      recyclabilityScore: 80,
      maxRecycleLoops: 99,
    },
    typicalSources: ['Vehicle maintenance', 'Quick-lube shops', 'Fleet operations', 'Marine engines'],
    endMarkets: ['Re-refined base oil', 'Industrial burner fuel', 'Asphalt flux', 'Marine fuel'],
    notes: 'Positive value - established recycling market. Re-refining preferred over burning.',
  },

  {
    id: '4.2.2-hydraulic-oil',
    class: 4,
    subclass: '4.2',
    sku: 'CHEM-HYD-OIL',
    tradeName: 'Used Hydraulic Oil',
    alternativeNames: ['Waste hydraulic fluid', 'Used ISO 32/46/68'],
    ewcCode: '13 01 10*',
    ewcDescription: 'mineral-based non-chlorinated hydraulic oils',
    wasteTier: 'T4',
    wasteTierDescription: 'Hazardous waste oil',
    hazard: {
      unNumber: 'UN 3082',
      adrClass: '9',
      packingGroup: 'III',
      hProperties: ['H5', 'H14'],
      transportRestrictions: 'Marine pollutant',
    },
    specifications: {
      composition: [
        { element: 'Mineral oil base', range: { min: 85, max: 95 }, unit: '%' },
        { element: 'Additives (AW, VI improvers)', range: { min: 3, max: 10 }, unit: '%' },
        { element: 'Wear metals and contaminants', range: { min: 0.5, max: 5 }, unit: '%' },
      ],
      physicalForm: 'Liquid',
      bulkDensity: { min: 860, max: 900, unit: 'kg/mÂ³' },
    },
    pricing: {
      basePrice: 95,
      unit: 't',
      range: { min: 50, max: 160 },
      marketIndex: 'OPIS',
      updateFrequency: 'weekly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'Low wear metals, single grade, clean, filterable for reuse', priceMultiplier: 1.35, contaminationMax: 1.0, certificationRequired: false },
      { tier: 'Q2', requirements: 'Clean hydraulic oil, suitable for re-refining', priceMultiplier: 1.15, contaminationMax: 3.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Standard used hydraulic oil', priceMultiplier: 1.0, contaminationMax: 5.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'Contaminated with water or other fluids', priceMultiplier: 0.65, contaminationMax: 15.0, certificationRequired: false },
    ],
    processing: {
      recyclingRoutes: ['Filtration and reuse', 'Re-refining', 'Industrial fuel'],
      specialRequirements: 'Check for water contamination. Test viscosity grade.',
      difficulty: 'easy',
      energyRequired: 0.6,
      equipmentNeeded: ['Vacuum dehydration', 'Particle filtration', 'Clay filtration'],
    },
    marketData: {
      demand: 'high',
      supply: 'high',
      volatility: 'low',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 400,
      carbonAvoided: 2300,
      recyclabilityScore: 85,
      maxRecycleLoops: 99,
    },
    typicalSources: ['Manufacturing plants', 'Construction equipment', 'Material handling', 'Mobile hydraulics'],
    endMarkets: ['Reconditioned hydraulic oil', 'Re-refined base oil', 'Industrial fuel'],
    notes: 'High-quality waste oil. Good market for re-refining. Cleaner than motor oil.',
  },

  {
    id: '4.2.3-transformer-oil',
    class: 4,
    subclass: '4.2',
    sku: 'CHEM-TRANS-OIL',
    tradeName: 'Used Transformer Oil',
    alternativeNames: ['Insulating oil', 'Dielectric oil'],
    ewcCode: '13 03 07*',
    ewcDescription: 'mineral-based non-chlorinated insulating and heat transmission oils',
    wasteTier: 'T4',
    wasteTierDescription: 'Hazardous waste - must test for PCBs',
    hazard: {
      unNumber: 'UN 3082',
      adrClass: '9',
      packingGroup: 'III',
      hProperties: ['H5', 'H14'],
      transportRestrictions: 'Test for PCBs before transport. If >50ppm PCB, special disposal required.',
    },
    specifications: {
      composition: [
        { element: 'Mineral oil', range: { min: 98, max: 100 }, unit: '%' },
        { element: 'Oxidation products', range: { min: 0, max: 2 }, unit: '%' },
      ],
      physicalForm: 'Liquid',
      bulkDensity: { min: 860, max: 895, unit: 'kg/mÂ³' },
    },
    pricing: {
      basePrice: 120,
      unit: 't',
      range: { min: -200, max: 250 },
      marketIndex: 'OPIS',
      updateFrequency: 'monthly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: 'PCB <2ppm, low acidity, good dielectric, reclaim-ready', priceMultiplier: 2.00, contaminationMax: 0.5, certificationRequired: true },
      { tier: 'Q2', requirements: 'PCB <50ppm, acceptable for re-refining', priceMultiplier: 1.0, contaminationMax: 2.0, certificationRequired: true },
      { tier: 'Q3', requirements: 'PCB >50ppm - requires destruction', priceMultiplier: -1.50, contaminationMax: 100.0, certificationRequired: true },],
      processing: {
        recyclingRoutes: ['Reclaiming/regeneration', 'Re-refining', 'Destruction (if PCB-contaminated)'],
      specialRequirements: 'MANDATORY PCB testing. Special handling if PCB detected.',
      difficulty: 'medium',
      energyRequired: 1.0,
      equipmentNeeded: ['PCB test kit', 'Reclaiming columns', 'Re-refining unit'],
    },
    marketData: {
      demand: 'medium',
      supply: 'low',
      volatility: 'high',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 380,
      carbonAvoided: 2620,
      recyclabilityScore: 90,
      maxRecycleLoops: 99,
    },
    typicalSources: ['Electrical utilities', 'Transformer maintenance', 'Substations'],
    endMarkets: ['Reclaimed transformer oil', 'Re-refined base oil', 'Destruction (if PCB+)'],
    notes: 'High-value if PCB-free. Negative value if PCB-contaminated (disposal cost). Always test before purchase.',
  },

  // 4.3 SOLVENTS - 5 SKUs
  {
    id: '4.3.1-ipa-used',
    class: 4,
    subclass: '4.3',
    sku: 'CHEM-IPA',
    tradeName: 'Isopropyl Alcohol (Used)',
    alternativeNames: ['IPA', 'Isopropanol', '2-propanol'],
    ewcCode: '14 06 03*',
    ewcDescription: 'other solvents and solvent mixtures',
    wasteTier: 'T4',
    wasteTierDescription: 'Hazardous flammable solvent',
    hazard: {
      unNumber: 'UN 1219',
      adrClass: '3',
      packingGroup: 'II',
      hProperties: ['H3', 'H5'],
      transportRestrictions: 'Flammable liquid - ADR Class 3. Keep away from ignition sources.',
    },
    specifications: {
      composition: [
        { element: 'Isopropanol', range: { min: 70, max: 99 }, unit: '%' },
        { element: 'Water', range: { min: 1, max: 20 }, unit: '%' },
        { element: 'Contaminants', range: { min: 0, max: 10 }, unit: '%' },
      ],
      physicalForm: 'Liquid',
      bulkDensity: { min: 786, max: 850, unit: 'kg/mÂ³' },
    },
    pricing: {
      basePrice: 180,
      unit: 't',
      range: { min: 80, max: 320 },
      marketIndex: 'ICIS',
      updateFrequency: 'weekly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: '>95% IPA, low contaminants, distillable to tech grade', priceMultiplier: 1.50, contaminationMax: 2.0, certificationRequired: false },
      { tier: 'Q2', requirements: '85-95% IPA, suitable for distillation', priceMultiplier: 1.0, contaminationMax: 10.0, certificationRequired: false },
      { tier: 'Q3', requirements: '70-85% IPA, needs purification', priceMultiplier: 0.60, contaminationMax: 20.0, certificationRequired: false },
      { tier: 'Q4', requirements: '<70% IPA or heavily contaminated', priceMultiplier: 0.30, contaminationMax: 40.0, certificationRequired: false },
    ],
    processing: {
      recyclingRoutes: ['Distillation and purification', 'Industrial fuel'],
      specialRequirements: 'Flammable - explosion-proof equipment. Store in cool area.',
      difficulty: 'medium',
      energyRequired: 1.8,
      equipmentNeeded: ['Distillation column', 'ATEX-rated equipment', 'Fire suppression'],
    },
    marketData: {
      demand: 'high',
      supply: 'high',
      volatility: 'medium',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 550,
      carbonAvoided: 1250,
      recyclabilityScore: 85,
      maxRecycleLoops: 99,
    },
    typicalSources: ['Electronics manufacturing', 'Pharmaceutical production', 'Cleaning operations', 'Paint shops'],
    endMarkets: ['Technical grade IPA', 'Cleaning solvent', 'Industrial fuel'],
    notes: 'High recovery value if clean. Distillation recovers >90%. Positive economics.',
  },

  {
    id: '4.3.2-acetone-used',
    class: 4,
    subclass: '4.3',
    sku: 'CHEM-ACET',
    tradeName: 'Acetone (Used)',
    alternativeNames: ['Propanone', 'Dimethyl ketone'],
    ewcCode: '14 06 03*',
    ewcDescription: 'other solvents and solvent mixtures',
    wasteTier: 'T4',
    wasteTierDescription: 'Hazardous flammable solvent',
    hazard: {
      unNumber: 'UN 1090',
      adrClass: '3',
      packingGroup: 'II',
      hProperties: ['H3', 'H5'],
      transportRestrictions: 'Highly flammable liquid - ADR Class 3.',
    },
    specifications: {
      composition: [
        { element: 'Acetone', range: { min: 75, max: 99 }, unit: '%' },
        { element: 'Water', range: { min: 1, max: 15 }, unit: '%' },
        { element: 'Other solvents/contaminants', range: { min: 0, max: 10 }, unit: '%' },
      ],
      physicalForm: 'Liquid',
      bulkDensity: { min: 791, max: 850, unit: 'kg/mÂ³' },
    },
    pricing: {
      basePrice: 210,
      unit: 't',
      range: { min: 100, max: 380 },
      marketIndex: 'ICIS',
      updateFrequency: 'weekly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: '>95% acetone, distillable to technical grade', priceMultiplier: 1.45, contaminationMax: 3.0, certificationRequired: false },
      { tier: 'Q2', requirements: '85-95% acetone', priceMultiplier: 1.0, contaminationMax: 10.0, certificationRequired: false },
      { tier: 'Q3', requirements: '75-85% acetone', priceMultiplier: 0.65, contaminationMax: 20.0, certificationRequired: false },
      { tier: 'Q4', requirements: '<75% acetone or multi-solvent mix', priceMultiplier: 0.35, contaminationMax: 35.0, certificationRequired: false },],
      processing: {
        recyclingRoutes: ['Distillation', 'Purification', 'Industrial fuel'],
      specialRequirements: 'Extremely flammable. ATEX Zone 0/1 equipment required.',
      difficulty: 'medium',
      energyRequired: 1.6,
      equipmentNeeded: ['Distillation unit', 'ATEX-rated area', 'Vapor recovery'],
    },
    marketData: {
      demand: 'high',
      supply: 'medium',
      volatility: 'high',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 480,
      carbonAvoided: 1720,
      recyclabilityScore: 90,
      maxRecycleLoops: 99,
    },
    typicalSources: ['Paint and coatings', 'Fiberglass manufacturing', 'Nail polish production', 'Cleaning operations'],
    endMarkets: ['Technical grade acetone', 'Nail polish remover', 'Industrial cleaner'],
    notes: 'Good recycling economics. Low boiling point (56Â°C) makes distillation easy.',
  },

  {
    id: '4.3.3-mek-used',
    class: 4,
    subclass: '4.3',
    sku: 'CHEM-MEK',
    tradeName: 'MEK (Methyl Ethyl Ketone) Used',
    alternativeNames: ['2-butanone', 'Ethyl methyl ketone'],
    ewcCode: '14 06 03*',
    ewcDescription: 'other solvents and solvent mixtures',
    wasteTier: 'T4',
    wasteTierDescription: 'Hazardous flammable solvent',
    hazard: {
      unNumber: 'UN 1193',
      adrClass: '3',
      packingGroup: 'II',
      hProperties: ['H3', 'H5', 'H7'],
      transportRestrictions: 'Flammable liquid. Reproductive toxicity concern.',
    },
    specifications: {
      composition: [
        { element: 'MEK', range: { min: 70, max: 99 }, unit: '%' },
        { element: 'Other ketones/solvents', range: { min: 1, max: 20 }, unit: '%' },
      ],
      physicalForm: 'Liquid',
      bulkDensity: { min: 805, max: 850, unit: 'kg/mÂ³' },
    },
    pricing: {
      basePrice: 195,
      unit: 't',
      range: { min: 90, max: 350 },
      marketIndex: 'ICIS',
      updateFrequency: 'weekly',
    },
    qualityTiers: [
      { tier: 'Q1', requirements: '>92% MEK, distillable', priceMultiplier: 1.40, contaminationMax: 5.0, certificationRequired: false },
      { tier: 'Q2', requirements: '80-92% MEK', priceMultiplier: 1.0, contaminationMax: 15.0, certificationRequired: false },
      { tier: 'Q3', requirements: '70-80% MEK', priceMultiplier: 0.60, contaminationMax: 25.0, certificationRequired: false },
    ],
    processing: {
      recyclingRoutes: ['Distillation', 'Industrial fuel'],
      specialRequirements: 'Flammable. ATEX equipment.',
      difficulty: 'medium',
      energyRequired: 1.7,
      equipmentNeeded: ['Distillation column', 'ATEX area'],
    },
    marketData: {
      demand: 'medium',
      supply: 'medium',
      volatility: 'medium',
      seasonality: false,
    },
    environmental: {
      carbonFootprint: 520,
      carbonAvoided: 1580,
      recyclabilityScore: 85,
      maxRecycleLoops: 99,
    },
    typicalSources: ['Adhesive production', 'Printing inks', 'Coatings', 'Dewaxing operations'],
    endMarkets: ['Technical grade MEK', 'Industrial coatings', 'Adhesives'],
    notes: 'Common industrial solvent. Good recovery rates via distillation.',
  },

  // 4.4 COOLANTS & GLYCOLS - 4 SKUs
  {
    id: '4.4.1-antifreeze-used',
    class: 4,
    subclass: '4.4',
    sku: 'CHEM-AFREZ',
    tradeName: 'Used Antifreeze/Coolant',
    alternativeNames: ['Used ethylene glycol', 'Spent coolant', 'Radiator fluid'],
    ewcCode: '16 01 14*',
    ewcDescription: 'antifreeze fluids containing dangerous substances',
    wasteTier: 'T4',
    wasteTierDescription: 'Hazardous waste - toxic glycol contaminated with heavy metals',
    hazard: {
      unNumber: 'UN 3082',
      adrClass: '9',
      packingGroup: 'III',
      hProperties: ['H5', 'H6', 'H14'],
      transportRestrictions: 'Toxic if ingested. Contains lead and other heavy metals.',
    },
    specifications: {
      composition: [
        { element: 'Ethylene glycol or propylene glycol', range: { min: 40, max: 95 }, unit: '%' },
        { element: 'Water', range: { min: 5, max: 50 }, unit: '%' },
        { element: 'Inhibitors and metals (Pb, Cu, Zn)', range: { min: 0.1, max: 5 }, unit: '%' },
      ],
      physicalForm: 'Liquid',
      bulkDensity: { min: 1050, max: 1130, unit: 'kg/mÂ³' },
    },
    pricing: {
      basePrice: -20,
      unit: 't',
      range: { min: -60, max: 40 },
      marketIndex: 'ICIS',
      updateFrequency: 'monthly',
    },
    qualityTiers: [
      { tier: 'Q2', requirements: 'High glycol content (>80%), low metals, single-source', priceMultiplier: 1.80, contaminationMax: 2.0, certificationRequired: false },
      { tier: 'Q3', requirements: 'Standard used antifreeze', priceMultiplier: 1.0, contaminationMax: 5.0, certificationRequired: false },
      { tier: 'Q4', requirements: 'Contaminated with oil or high metals', priceMultiplier: 0.50, contaminationMax: 15.0, certificationRequired: false },],
      processing: {
        recyclingRoutes: ['Vacuum distillation', 'Filtration and reuse', 'Incineration'],
      specialRequirements: 'Remove heavy metals. Test glycol type (EG vs PG).',
      difficulty: 'medium',
      energyRequired: 2.2,
      equipmentNeeded: ['Vacuum distillation', 'Heavy metal precipitation', 'Ion exchange'],
    },
    marketData: {
      demand: 'medium',
      supply: 'very-high',
      volatility: 'low',
      seasonality: true,
    },
    environmental: {
      carbonFootprint: 720,
      carbonAvoided: 1280,
      recyclabilityScore: 70,
      maxRecycleLoops: 99,
    },
    typicalSources: ['Automotive service', 'Fleet maintenance', 'Industrial cooling systems'],
    endMarkets: ['Reclaimed antifreeze', 'Industrial coolant base', 'Waste-to-energy'],
    notes: 'Seasonal collection (fall/winter). Ethylene glycol toxic - propylene glycol preferred for safety.',
  },
];

export const PROCESS_CHEMICALS_CLASS: MaterialClass = {
  classNumber: 4,
  className: 'Process Chemicals',
  description: 'Used metalworking fluids, oils, solvents - mostly hazardous waste',
  skuCount: 20,
  materials: PROCESS_CHEMICALS,
};

export default PROCESS_CHEMICALS;
